import type { Card } from "@pitch-storm/shared";

const PLOT_CARDS: Card[] = [
  { id: "plot-1", type: "plot", text: "gets in big trouble with the mafia." },
  { id: "plot-2", type: "plot", text: "joins the army to save their aging father in medieval China." },
  { id: "plot-3", type: "plot", text: "tries to take down the top flute player in the band." },
  { id: "plot-4", type: "plot", text: "travels through time to save the world." },
  { id: "plot-5", type: "plot", text: "battles a swarm of radioactive mutants." },
  { id: "plot-6", type: "plot", text: "tries to break the record for baking the worlds largest pizza." },
  { id: "plot-7", type: "plot", text: "accidentally starts WWIII." },
  { id: "plot-8", type: "plot", text: "fights a gang of bullies at school." },
  { id: "plot-9", type: "plot", text: "hunts for bigfoot." },
  { id: "plot-10", type: "plot", text: "must stop a child mayor from bankrupting their hometown." },
  { id: "plot-11", type: "plot", text: "competes in fast and furious illegal street racing." },
  { id: "plot-12", type: "plot", text: "becomes trapped in a dangerous video game." },
  { id: "plot-13", type: "plot", text: "tries to solve a mystery deep under the Pacific Ocean." },
  { id: "plot-14", type: "plot", text: "discovers a terrible secret about their own family." },
  { id: "plot-15", type: "plot", text: "goes on the run in New Zealand bush country." },
  { id: "plot-16", type: "plot", text: "incites a rebellion in an oppressed insane asylum." },
  { id: "plot-17", type: "plot", text: "tries to escape from hell." },
  { id: "plot-18", type: "plot", text: "battles addiction to prescription drugs." },
  { id: "plot-19", type: "plot", text: "makes a deal with the devil." },
  { id: "plot-20", type: "plot", text: "competes in a deadly reality TV competition." },
  { id: "plot-21", type: "plot", text: "tries to save as many people as possible from Nazis in WWII." },
  { id: "plot-22", type: "plot", text: "goes on a terrible drug trip during a family reunion." },
  { id: "plot-23", type: "plot", text: "struggles to adjust to civilian life after returning from the war." },
  { id: "plot-24", type: "plot", text: "crashes their plane in the Canadian wilderness." },
  { id: "plot-25", type: "plot", text: "must transport a dangerous criminal across a war-torn city." },
  { id: "plot-26", type: "plot", text: "struggles to raise a family in the Wild West." },
  { id: "plot-27", type: "plot", text: "goes undercover in the world of hip-hop culture." },
  { id: "plot-28", type: "plot", text: "tries to save the world from zombie apocalypse." },
  { id: "plot-29", type: "plot", text: "in an awkward teenage romance." },
  { id: "plot-30", type: "plot", text: "tries to stop a ferry boat from sinking." },
  { id: "plot-31", type: "plot", text: "invents a gadget that will change the world." },
  { id: "plot-32", type: "plot", text: "robs a bank to get themselves out of debt." },
  { id: "plot-33", type: "plot", text: "throws the greatest house party ever!" },
  { id: "plot-34", type: "plot", text: "throws a bachelor/ette party that goes terribly wrong." },
  { id: "plot-35", type: "plot", text: "is mistakenly sent to heaven." },
  { id: "plot-36", type: "plot", text: "leads a deadly rescue mission on Mt. Everest." },
  { id: "plot-37", type: "plot", text: "gets kidnapped by malevolent sock puppets." },
  { id: "plot-38", type: "plot", text: "races around the world in a hot air balloon." },
  { id: "plot-39", type: "plot", text: "explores a dangerous alien planet." },
  { id: "plot-40", type: "plot", text: "tries to escape an island full of hungry dinosaurs." },
  { id: "plot-41", type: "plot", text: "seeks their fortune during the Alaskan Gold Rush." },
  { id: "plot-42", type: "plot", text: "has a steamy affair with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-43", type: "plot", text: "teaches poor kids to read." },
  { id: "plot-44", type: "plot", text: "falls for a dangerous femme fatale." },
  { id: "plot-45", type: "plot", text: "tries to disarm a series of devilish traps." },
  { id: "plot-46", type: "plot", text: "embarks on the first human colonization mission to another galaxy." },
  { id: "plot-47", type: "plot", text: "gets lost in the Amazon jungle." },
  { id: "plot-48", type: "plot", text: "must finish a dangerous supernatural board game to survive." },
  { id: "plot-49", type: "plot", text: "searches for enlightenment in the far corners of the earth." },
  { id: "plot-50", type: "plot", text: "is the only witness to a mafia killing." },
  { id: "plot-51", type: "plot", text: "pilots a giant robot to save the world from monsters." },
  { id: "plot-52", type: "plot", text: "goes undercover as a flamenco dancer to hide from the mob." },
  { id: "plot-53", type: "plot", text: "tries to save their family from kidnappers." },
  { id: "plot-54", type: "plot", text: "struggles with the bleak reality of life in the big city." },
  { id: "plot-55", type: "plot", text: "races to stop the detonation of a biological weapon in New York City." },
  { id: "plot-56", type: "plot", text: "leads a rebellion against a totalitarian regime." },
  { id: "plot-57", type: "plot", text: "trapped on Mt. Everest during a deadly storm." },
  { id: "plot-58", type: "plot", text: "will do anything for fame on a reality TV show." },
  { id: "plot-59", type: "plot", text: "discovers a hidden island full of mythical creatures." },
  { id: "plot-60", type: "plot", text: "tries to scam their way to fame in Hollywood." },
  { id: "plot-61", type: "plot", text: "hosts the worlds worst houseguest." },
  { id: "plot-62", type: "plot", text: "makes contact with dangerous aliens." },
  { id: "plot-63", type: "plot", text: "goes on a quest to slay a dragon." },
  { id: "plot-64", type: "plot", text: "hunts for elves in a mysterious forest." },
  { id: "plot-65", type: "plot", text: "goes on the run to escape deadly assassins." },
  { id: "plot-66", type: "plot", text: "searches for the cure of a deadly plague." },
  { id: "plot-67", type: "plot", text: "hunts and is hunted by a deadly serial killer." },
  { id: "plot-68", type: "plot", text: "is kidnapped by terrorists!" },
  { id: "plot-69", type: "plot", text: "is accidentally elected president of the United States." },
  { id: "plot-70", type: "plot", text: "treks across a dangerous desert to save their friends." },
  { id: "plot-71", type: "plot", text: "gets trapped in the body of a bear." },
  { id: "plot-72", type: "plot", text: "embarks on an epic journey to destroy an evil magical artifact." },
  { id: "plot-73", type: "plot", text: "only has one month to complete their bucket list." },
  { id: "plot-74", type: "plot", text: "competes against the rich kid team in a heartwarming underdog story." },
  { id: "plot-75", type: "plot", text: "fights to thwart an ancient and unstoppable evil." },
  { id: "plot-76", type: "plot", text: "outwits gangsters and cops in a series of death-defying car chases." },
  { id: "plot-77", type: "plot", text: "goes on a mad quest to kill the whale that ate their dog." },
  { id: "plot-78", type: "plot", text: "stranded on a lifeboat with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-79", type: "plot", text: "discovers a dangerous secret at a popular new theme park." },
  { id: "plot-80", type: "plot", text: "on a quest for a treasure that will save the kingdom." },
  { id: "plot-81", type: "plot", text: "must stop their evil twin from ruining their life!" },
  { id: "plot-82", type: "plot", text: "becomes a vigilante to rid their city of crime." },
  { id: "plot-83", type: "plot", text: "gets an exciting new job working for ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-84", type: "plot", text: "steals from the rich and gives to the poor and becomes a local legend." },
  { id: "plot-85", type: "plot", text: "attempts a desperate escape from Seaworld." },
  { id: "plot-86", type: "plot", text: "will do whatever it takes to become a world-famous chef." },
  { id: "plot-87", type: "plot", text: "fights in bloody gladiator death matches." },
  { id: "plot-88", type: "plot", text: "fights for the ultimate boxing title." },
  { id: "plot-89", type: "plot", text: "discovers the mythical city of El Dorado." },
  { id: "plot-90", type: "plot", text: "competes in a deadly underground martial arts tournament." },
  { id: "plot-91", type: "plot", text: "tries to steal the Declaration of Independence." },
  { id: "plot-92", type: "plot", text: "inherits an evil doll." },
  { id: "plot-93", type: "plot", text: "fights to stop an evil AI from destroying humanity." },
  { id: "plot-94", type: "plot", text: "faces a difficult choice between love and money." },
  { id: "plot-95", type: "plot", text: "receives an unexpected message from God." },
  { id: "plot-96", type: "plot", text: "leads the rescue mission for a missing child." },
  { id: "plot-97", type: "plot", text: "wins big at a casino and becomes the target of the mafia." },
  { id: "plot-98", type: "plot", text: "tries to capture a giant ape on a mysterious island." },
  { id: "plot-99", type: "plot", text: "fights a huge angry bear." },
  { id: "plot-100", type: "plot", text: "battles corruption in the greeting card industry." },
  { id: "plot-101", type: "plot", text: "on a deadly white-water rafting trip." },
  { id: "plot-102", type: "plot", text: "fights in a boxing match against their ultimate rival: ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-103", type: "plot", text: "building a rocketship to escape a dying planet." },
  { id: "plot-104", type: "plot", text: "accidentally joins a cult on their first day in college." },
  { id: "plot-105", type: "plot", text: "involved in a complicated love triangle." },
  { id: "plot-106", type: "plot", text: "leads a slave rebellion in ancient Rome." },
  { id: "plot-107", type: "plot", text: "fights against evil robots that look like people." },
  { id: "plot-108", type: "plot", text: "discovers the fountain of youth." },
  { id: "plot-109", type: "plot", text: "flees from a tribe of cannibals." },
  { id: "plot-110", type: "plot", text: "in a series of romantic misadventures." },
  { id: "plot-111", type: "plot", text: "falls madly in love with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-112", type: "plot", text: "discovers a map leading to a legendary treasure hoard." },
  { id: "plot-113", type: "plot", text: "on a quest to discover Atlantis." },
  { id: "plot-114", type: "plot", text: "fights to save a rare and mysterious animal from poachers." },
  { id: "plot-115", type: "plot", text: "plots to escape a retirement home in Florida." },
  { id: "plot-116", type: "plot", text: "attempts to rescue hostages from a skyscraper." },
  { id: "plot-117", type: "plot", text: "tries to steal the worlds largest diamond." },
  { id: "plot-118", type: "plot", text: "fights to take down a dangerous cult." },
  { id: "plot-119", type: "plot", text: "struggles to bring their best friend back from the dead." },
  { id: "plot-120", type: "plot", text: "competes on a cooking game show to pay for their mom's medical bills." },
  { id: "plot-121", type: "plot", text: "matches wits against a wily leprechaun." },
  { id: "plot-122", type: "plot", text: "struggles to survive after a deadly shipwreck." },
  { id: "plot-123", type: "plot", text: "gets trapped overnight in a haunted asylum." },
  { id: "plot-124", type: "plot", text: "discovers a conspiracy of lizard people in the government." },
  { id: "plot-125", type: "plot", text: "has just two hours to find a huge amount of money for a dangerous mobster." },
  { id: "plot-126", type: "plot", text: "must protect their small village from a horde of bandits." },
  { id: "plot-127", type: "plot", text: "leads a ragtag crew of pirates against the British Navy." },
  { id: "plot-128", type: "plot", text: "is abducted by aliens!" },
  { id: "plot-129", type: "plot", text: "makes a selfish wish in a demonic wishing well." },
  { id: "plot-130", type: "plot", text: "haunted by the angry ghost of ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-131", type: "plot", text: "searches for peace in a dangerous radioactive wasteland." },
  { id: "plot-132", type: "plot", text: "is stranded on a desert island." },
  { id: "plot-133", type: "plot", text: "tries to save a family of Bigfoots from a deadly wildfire." },
  { id: "plot-134", type: "plot", text: "struggles to write the next great American novel." },
  { id: "plot-135", type: "plot", text: "fights to save their family from demonic possession." },
  { id: "plot-136", type: "plot", text: "will do whatever it takes to save the local library." },
  { id: "plot-137", type: "plot", text: "struggles to rebuild their community after a devastating hurricane." },
  { id: "plot-138", type: "plot", text: "accidentally becomes the Pope." },
  { id: "plot-139", type: "plot", text: "falls in love with a merperson." },
  { id: "plot-140", type: "plot", text: "tries to escape from the sinking city of Atlantis." },
  { id: "plot-141", type: "plot", text: "becomes worshipped as gods by a primitive culture." },
  { id: "plot-142", type: "plot", text: "battles an evil possessed book in a bookstore." },
  { id: "plot-143", type: "plot", text: "trapped in a dark version of our own reality." },
  { id: "plot-144", type: "plot", text: "goes for gold in Olympic figure skating." },
  { id: "plot-145", type: "plot", text: "must win enough money at the talent show to pay for their grandma's surgery." },
  { id: "plot-146", type: "plot", text: "searches for a stolen nuclear bomb." },
  { id: "plot-147", type: "plot", text: "goes on a dangerous ocean voyage." },
  { id: "plot-148", type: "plot", text: "tries to save their small beach town from a monstrous seal." },
  { id: "plot-149", type: "plot", text: "is held hostage at a karaoke bar run by monsters." },
  { id: "plot-150", type: "plot", text: "discovers the secret world of modern wizards." },
  { id: "plot-151", type: "plot", text: "fights a supernatural killer clown." },
  { id: "plot-152", type: "plot", text: "goes on a quest for the Holy Grail." },
  { id: "plot-153", type: "plot", text: "goes back in time to kill Hitler." },
  { id: "plot-154", type: "plot", text: "protecting the world's last unicorn from an evil cosmetics company." },
  { id: "plot-155", type: "plot", text: "flees from natural disaster in a near-future apocalypse." },
  { id: "plot-156", type: "plot", text: "learns that they are heir to the throne of an ancient kingdom." },
  { id: "plot-157", type: "plot", text: "discovering the true origins of Santa Claus." },
  { id: "plot-158", type: "plot", text: "steals a magical treasure from a dangerous witch." },
  { id: "plot-159", type: "plot", text: "navigates the secret world of modern vampires." },
  { id: "plot-160", type: "plot", text: "Choose the plot of your favourite video game. Your movie is an adaptation of that plot.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-161", type: "plot", text: "Choose a plot previously pitched by another player. Your movie is a broadway adaptation of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-162", type: "plot", text: "Choose a plot previously pitched by another player. Your movie is a hilarious spoof of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-163", type: "plot", text: "Choose the plot to your favourite movie. Your movie is a gritty reboot of that idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-164", type: "plot", text: "Choose the plot to your favourite book. Your movie is an adaptation of that book.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-165", type: "plot", text: "Choose a plot previously pitched. Your movie is a gritty reboot of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-166", type: "plot", text: "Choose the plot of your favourite movie. This is another sequel to that movie.", header: "FRANCHISE PITCH:", isFranchise: true },
];

const CHARACTER_CARDS: Card[] = [
  { id: "char-1", type: "character", header: "EXT. DREARY ORPHANAGE", text: "A sad, sad orphan looking for a new family" },
  { id: "char-2", type: "character", header: "EXT. OUT BY THE WELL", text: "A dog just trying to rescue his boy" },
  { id: "char-3", type: "character", header: "INT. COMMAND CENTER", text: "A heroic young naval officer" },
  { id: "char-4", type: "character", header: "EXT. JUNKYARD", text: "A dog who never had a home" },
  { id: "char-5", type: "character", header: "INT. TOP-SECRET FACILITY", text: "The world's first sentient A.I." },
  { id: "char-6", type: "character", header: "EXT. CITY ROOFTOPS", text: "An untrained vigilante" },
  { id: "char-7", type: "character", header: "INT. YMCA", text: "A senior citizen swim team" },
  { id: "char-8", type: "character", header: "EXT. FRUIT MARKET", text: "A pineapple with a heart of gold" },
  { id: "char-9", type: "character", header: "INT. BUSY RESTAURANT", text: "A clumsy but loveable waitress" },
  { id: "char-10", type: "character", header: "INT. GROCERY STORE", text: "An authoritarian grocery store manager" },
  { id: "char-11", type: "character", header: "EXT. RUN-DOWN HOUSE", text: "A witch living on the edge of town" },
  { id: "char-12", type: "character", header: "INT. JEFF'S BASEMENT", text: "A pair of stoners that just ran out of weed" },
  { id: "char-13", type: "character", header: "EXT. THE SIDE OF THE ROAD", text: "A dysfunctional family on a road trip" },
  { id: "char-14", type: "character", header: "INT. KARAOKE BAR", text: "A country singer determined to make it big in Nashville" },
  { id: "char-15", type: "character", header: "INT. HIGH-SECURITY LAB", text: "A group of scientists on the brink of resurrecting dinosaurs" },
  { id: "char-16", type: "character", header: "INT. OIL FIELDS", text: "A corrupt oil baron that will do anything for profit" },
  { id: "char-17", type: "character", header: "INT. CITY LIBRARY", text: "A bookish librarian that just wants to be left alone" },
  { id: "char-18", type: "character", header: "EXT. PARISIAN STREET", text: "A mime with magical powers" },
  { id: "char-19", type: "character", header: "EXT. DAYCARE CENTER", text: "An overworked single parent" },
  { id: "char-20", type: "character", header: "INT. CELEBRITY MANSION", text: "The producer of a trashy reality show" },
  { id: "char-21", type: "character", header: "INT. ARCADE", text: "A videogame character comes to life" },
  { id: "char-22", type: "character", header: "INT. POLICE STATION", text: "An innocent person framed for murder" },
  { id: "char-23", type: "character", header: "EXT. TRANSYLVANIAN CASTLE", text: "An ancient and powerful vampire" },
  { id: "char-24", type: "character", header: "INT. KITCHEN", text: "A small mouse with a big heart" },
  { id: "char-25", type: "character", header: "EXT. CELEBRITY MANSION", text: "An A-list Hollywood star on the edge of bankruptcy" },
  { id: "char-26", type: "character", header: "INT. BAND CLASS", text: "The world's hottest oboe player" },
  { id: "char-27", type: "character", header: "EXT. MYSTERIOUS FOREST", text: "A friendly dragon living in the forest" },
  { id: "char-28", type: "character", header: "INT. WIZARD'S STUDY", text: "An old wizard in need of an apprentice" },
  { id: "char-29", type: "character", header: "EXT. THE JUNGLE", text: "A feral child raised by apes" },
  { id: "char-30", type: "character", header: "INT. HOSPITAL", text: "A surgeon with a fake medical degree" },
  { id: "char-31", type: "character", header: "EXT. THE OPEN OCEAN", text: "The passengers of an ill-fated luxury cruise" },
  { id: "char-32", type: "character", header: "INT. MANSION", text: "The leader of a powerful mob family" },
  { id: "char-33", type: "character", header: "INT. DIVE BAR", text: "An amateur metal band struggling to find a gig" },
  { id: "char-34", type: "character", header: "INT. ARCADE", text: "A charismatic slacker just out for a good time" },
  { id: "char-35", type: "character", header: "EXT. FOOTBALL FIELD", text: "A huge jock that just wants to be a ballerina" },
  { id: "char-36", type: "character", header: "INT. THE BRIDGE", text: "The roguish captain of an interstellar starship" },
  { id: "char-37", type: "character", header: "EXT. THE GRAND CANYON", text: "A daredevil with a deathwish" },
  { id: "char-38", type: "character", header: "INT. HAUNTED HOUSE", text: "A woman that can speak to ghosts" },
  { id: "char-39", type: "character", header: "INT. THE WHITE HOUSE", text: "The U.S. President" },
  { id: "char-40", type: "character", header: "INT. ANIMAL SHELTER", text: "The world's most adorable kitten" },
  { id: "char-41", type: "character", header: "EXT. ANCIENT RUINS", text: "A professor turned adventurer" },
  { id: "char-42", type: "character", header: "EXT. THE EDGE OF TOWN", text: "An old widow that everyone thinks is a witch" },
  { id: "char-43", type: "character", header: "INT. AREA 51", text: "A secret government agency protecting the world from aliens" },
  { id: "char-44", type: "character", header: "EXT. OLD WESTERN SALOON", text: "A cowboy left for dead and out for revenge" },
  { id: "char-45", type: "character", header: "EXT. BEHIND ENEMY LINES", text: "A group of soldiers on a suicide mission" },
  { id: "char-46", type: "character", header: "INT. GOVERNOR'S MANSION", text: "A magical nanny for a wealthy family" },
  { id: "char-47", type: "character", header: "EXT. FEUDAL JAPAN", text: "A young ninja on a quest to avenge their family" },
  { id: "char-48", type: "character", header: "EXT. THE OPEN ROAD", text: "A mysterious drifter from their past" },
  { id: "char-49", type: "character", header: "INT. DENNY'S", text: "A misunderstood old man" },
  { id: "char-50", type: "character", header: "INT. WALMART", text: "A has-been professional wrestler" },
  { id: "char-51", type: "character", header: "EXT. DEEP IN THE WOODS", text: "Two kids lost in the woods" },
  { id: "char-52", type: "character", header: "EXT. MYSTERIOUS ISLAND", text: "A crew of pirates on the hunt for treasure" },
  { id: "char-53", type: "character", header: "EXT. FIELDS OF BATTLE", text: "A noble barbarian from a distant land" },
  { id: "char-54", type: "character", header: "INT. HIP VAMPIRE CLUB", text: "An overweight vampire that just wants to fit in" },
  { id: "char-55", type: "character", header: "EXT. BAMBOO FOREST", text: "A young samurai on a quest to prove themselves" },
  { id: "char-56", type: "character", header: "INT. THE OPERATING ROOM", text: "An ensemble cast of sexy young E.R. doctors" },
  { id: "char-57", type: "character", header: "EXT. THE ENCHANTED FOREST", text: "Three little homeless pigs" },
  { id: "char-58", type: "character", header: "INT. THE EMBASSY", text: "A secret agent whose cover has just been blown" },
  { id: "char-59", type: "character", header: "INT. HEADMASTER'S STUDY", text: "The headmaster of a strict boarding school" },
  { id: "char-60", type: "character", header: "EXT. WORKING CLASS TOWN", text: "A grizzled veteran returning home" },
  { id: "char-61", type: "character", header: "INT. INTERNET CAFE", text: "The best hacker in the world" },
  { id: "char-62", type: "character", header: "EXT. THE COLISEUM", text: "A disgraced Roman general" },
  { id: "char-63", type: "character", header: "INT. MT. OLYMPUS", text: "Zeus, king of the gods" },
  { id: "char-64", type: "character", header: "INT. DINGY APARTMENT", text: "A desperate con artist struggling to feed their family" },
  { id: "char-65", type: "character", header: "EXT. THE OUTBACK", text: "A crocodile hunter who knows nothing about the big city" },
  { id: "char-66", type: "character", header: "EXT. MARTIAN DESERT", text: "The first human colonists on Mars" },
  { id: "char-67", type: "character", header: "EXT. DARK ALLEY", text: "A young superhero just discovering their powers" },
  { id: "char-68", type: "character", header: "EXT. CAMELOT", text: "The Knights of the Round Table" },
  { id: "char-69", type: "character", header: "INT. PRISTINE LAWN", text: "A grumpy old man that just wants his privacy" },
  { id: "char-70", type: "character", header: "EXT. GRUNGY STREET", text: "A professional hitman on their last job" },
  { id: "char-71", type: "character", header: "INT. CHILDREN'S HOSPITAL", text: "A friendly clown on a mission to make people happy" },
  { id: "char-72", type: "character", header: "INT. CONVENT", text: "A nun with a scandalous secret" },
  { id: "char-73", type: "character", header: "INT. CASTLE TOWER", text: "A princess determined to rescue herself" },
  { id: "char-74", type: "character", header: "EXT. DENNY'S PARKING LOT", text: "A group of friends on their last night before they all leave for college" },
  { id: "char-75", type: "character", header: "EXT. THE MAYOR'S OFFICE", text: "A ruthless politician hungry for power" },
  { id: "char-76", type: "character", header: "INT. LOFT APARTMENT", text: "A young artist struggling to pay rent" },
  { id: "char-77", type: "character", header: "EXT. SOCCER FIELD", text: "A soccer mom that is determined to help her kids win the big game" },
  { id: "char-78", type: "character", header: "INT. CHILD'S BEDROOM", text: "A childhood toy come to life" },
  { id: "char-79", type: "character", header: "INT. CHURCH BASEMENT", text: "A hip rapping youth pastor" },
  { id: "char-80", type: "character", header: "EXT. TUNDRA", text: "A tribe of cavemen hunting for food" },
  { id: "char-81", type: "character", header: "INT. FRAT HOUSE", text: "A fraternity on the verge of suspension" },
  { id: "char-82", type: "character", header: "INT. ART GALLERY", text: "A suave art thief" },
  { id: "char-83", type: "character", header: "EXT. STORMY SEA", text: "A grizzled sea captain" },
  { id: "char-84", type: "character", header: "INT. DOJO", text: "A martial arts master with a troubled past" },
  { id: "char-85", type: "character", header: "INT. TIDY APARTMENT", text: "A blind woman living by herself" },
  { id: "char-86", type: "character", header: "EXT. NEW YORK CITY", text: "Crime-fighting robots" },
  { id: "char-87", type: "character", header: "INT. INDUSTRIAL SITE", text: "Two secret agents deep undercover" },
  { id: "char-88", type: "character", header: "EXT. HIGH SCHOOL GYM", text: "A group of teens charged with protecting the world" },
  { id: "char-89", type: "character", header: "INT. COUNTRY CLERK'S OFFICE", text: "A journalist on the trail of a huge story" },
  { id: "char-90", type: "character", header: "INT. DIRTY APARTMENT", text: "A divorced dad trying to reconnect with his kids" },
  { id: "char-91", type: "character", header: "INT. SUBURBAN HOME", text: "A married couple going through a nasty divorce" },
  { id: "char-92", type: "character", header: "EXT. CONSTRUCTION SITE", text: "Friendly woodland creatures forced to flee their home because of pollution" },
  { id: "char-93", type: "character", header: "INT. THE GLOBE THEATRE", text: "Hot young William Shakespeare" },
  { id: "char-94", type: "character", header: "EXT. CENTRAL PARK", text: "A friendly talking dinosaur" },
  { id: "char-95", type: "character", header: "INT. AT THE CLUB", text: "A lifelong bachelor" },
  { id: "char-96", type: "character", header: "INT. CLONING LAB", text: "(Pick a historical figure)" },
  { id: "char-97", type: "character", header: "INT. CHILDREN'S THEATRE", text: "The world's greatest puppeteer" },
  { id: "char-98", type: "character", header: "INT. MANHATTAN OFFICE", text: "A sports writer looking for love" },
  { id: "char-99", type: "character", header: "EXT. ABANDONED HOUSE", text: "Confused ghosts that don't know they're dead" },
  { id: "char-100", type: "character", header: "EXT. DOWN THE STREET", text: "A group of kids solving a mystery at summer camp" },
  { id: "char-101", type: "character", header: "INT. RESEARCH FACILITY", text: "A troubled kid with supernatural powers" },
  { id: "char-102", type: "character", header: "INT. REBEL SPACESHIP", text: "A ragtag group of rebels" },
  { id: "char-103", type: "character", header: "EXT. FARM", text: "A little girl and her dog" },
  { id: "char-104", type: "character", header: "EXT. BOSTON WHARF", text: "A young gangster that will do anything to get to the top" },
  { id: "char-105", type: "character", header: "INT. MYSTERIOUS CAVE", text: "A genie trapped in a magic lamp" },
  { id: "char-106", type: "character", header: "INT. RURAL CHURCH", text: "A beguiling cult leader" },
  { id: "char-107", type: "character", header: "INT. SUSHI RESTAURANT", text: "A young couple on the verge of breaking up" },
  { id: "char-108", type: "character", header: "EXT. FOOTBALL FIELD", text: "A controversial small town football coach" },
  { id: "char-109", type: "character", header: "INT. UNDERSEA LABORATORY", text: "A shark with a human brain" },
  { id: "char-110", type: "character", header: "EXT. TROOP 514 TURF", text: "A gang of ruthless girl scouts" },
  { id: "char-111", type: "character", header: "EXT. DREARY GRAVEYARD", text: "A lonely gravedigger" },
  { id: "char-112", type: "character", header: "INT. AUDITION ROOM", text: "A plucky down-on-her-luck actress" },
  { id: "char-113", type: "character", header: "EXT. LOS ANGELES", text: "(Pick an actor/actress) Playing themselves" },
  { id: "char-114", type: "character", header: "INT. POLICE STATION", text: "A cop that plays it by the book" },
  { id: "char-115", type: "character", header: "INT. THE PRINCIPAL'S OFFICE", text: "A child genius with no social skills" },
  { id: "char-116", type: "character", header: "EXT. AT THE CLUB", text: "A fiery young rapper on their way to fame" },
  { id: "char-117", type: "character", header: "EXT. THE GARDEN", text: "An aging butler reminiscing about their glory days" },
  { id: "char-118", type: "character", header: "EXT. MEDIEVAL CASTLE", text: "A knight sworn to protect their kingdom" },
  { id: "char-119", type: "character", header: "INT. HUMAN HOME", text: "A bear disguised as a person" },
  { id: "char-120", type: "character", header: "INT. DINGY OFFICE", text: "A private detective following a dangerous trail of clues" },
  { id: "char-121", type: "character", header: "INT. AUTO-SHOP", text: "A down-on-their-luck auto mechanic" },
  { id: "char-122", type: "character", header: "EXT. STONE BRIDGE", text: "A misunderstood troll living under a bridge" },
  { id: "char-123", type: "character", header: "INT. BARRACKS", text: "A group of kids at boot camp" },
  { id: "char-124", type: "character", header: "INT. CONFESSIONAL BOOTH", text: "A priest suffering a crisis of faith" },
  { id: "char-125", type: "character", header: "INT. LIBRARY", text: "A fed up high school librarian with nothing to lose" },
  { id: "char-126", type: "character", header: "INT. VW BUS", text: "An aging hippie that longs for the good ole days" },
  { id: "char-127", type: "character", header: "INT. SWISS BANK", text: "A deadly assassin suffering from amnesia" },
  { id: "char-128", type: "character", header: "EXT. IDYLLIC VILLAGE", text: "A fellowship of unlikely heroes" },
  { id: "char-129", type: "character", header: "INT. GAMBLING HALL", text: "Two scoundrels out to make a fortune" },
  { id: "char-130", type: "character", header: "INT. BEAUTY PAGEANT", text: "A child beauty pageant queen" },
  { id: "char-131", type: "character", header: "INT. MODERN ART MUSEUM", text: "A snobby art critic" },
  { id: "char-132", type: "character", header: "EXT. RECESS", text: "The world's meanest ten-year-old bully" },
  { id: "char-133", type: "character", header: "INT. AIRPORT SECURITY", text: "A TSA agent fighting for justice" },
  { id: "char-134", type: "character", header: "EXT. THE WOODS", text: "A bunch of kids looking for adventure during summer vacation" },
  { id: "char-135", type: "character", header: "INT. BACKSTAGE", text: "An ambitious young pop-star" },
  { id: "char-136", type: "character", header: "INT. 1-BEDROOM APARTMENT", text: "A cat that will do anything to get fed" },
  { id: "char-137", type: "character", header: "EXT. MYSTERIOUS CASTLE", text: "A mad scientist conducting a world-changing experiment" },
  { id: "char-138", type: "character", header: "INT. ENCHANTED CASTLE", text: "A prince transformed into a monster" },
  { id: "char-139", type: "character", header: "INT. LIBERTY HALL", text: "The Founding Fathers" },
  { id: "char-140", type: "character", header: "INT. ASTRONOMY LAB", text: "An astronomer that thinks they've made contact with aliens" },
  { id: "char-141", type: "character", header: "INT. DINING HALL", text: "A lonely child at a boarding school" },
  { id: "char-142", type: "character", header: "EXT. TINY FISHING BOAT", text: "An old fisherman alone at sea" },
  { id: "char-143", type: "character", header: "INT. WASHINGTON D.C.", text: "A young politician with dreams of saving the world" },
  { id: "char-144", type: "character", header: "INT. CHILD'S BEDROOM", text: "A kid with a creepy imaginary friend" },
  { id: "char-145", type: "character", header: "INT. COFFEE SHOP", text: "A caveman recently brought back to life" },
  { id: "char-146", type: "character", header: "INT. NURSERY", text: "A wise-cracking baby" },
  { id: "char-147", type: "character", header: "EXT. MEXICAN RESORT TOWN", text: "A group of girls out for the BEST SPRING BREAK EVER" },
  { id: "char-148", type: "character", header: "EXT. WINDSWEPT PRAIRIE", text: "A stoic family of pioneers" },
  { id: "char-149", type: "character", header: "EXT. BBQ SHED", text: "A family of cannibal hillbillies" },
  { id: "char-150", type: "character", header: "EXT. HOLLYWOOD PARTY", text: "An ensemble cast of celebrities playing themselves" },
  { id: "char-151", type: "character", header: "INT. ICE SKATING RINK", text: "A competitive figure skater training to win the Grand Prix" },
  { id: "char-152", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie stars a younger version of that character.", isFranchise: true },
  { id: "char-153", type: "character", header: "FRANCHISE PITCH:", text: "Choose a mentor character from another player's previously pitched movie. Your movie is an origin story for that character.", isFranchise: true },
  { id: "char-154", type: "character", header: "FRANCHISE PITCH:", text: "Choose a love interest from another player's previously pitched movie.", isFranchise: true },
  { id: "char-155", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie is an off-brand knock off of their character.", isFranchise: true },
  { id: "char-156", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie features them as a grizzled veteran.", isFranchise: true },
  { id: "char-157", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie is about that character's children.", isFranchise: true },
  { id: "char-158", type: "character", header: "FRANCHISE PITCH:", text: "Choose a minor character from another player's previously pitched movie.", isFranchise: true },
  { id: "char-159", type: "character", header: "FRANCHISE PITCH:", text: "Choose a villain from another player's previously pitched movie.", isFranchise: true },
  { id: "char-160", type: "character", header: "FRANCHISE PITCH:", text: "Choose the hero of another player's previously pitched movie.", isFranchise: true },
  { id: "char-161", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie is the third movie in that trilogy.", isFranchise: true },
];

const NOTE_CARDS: Card[] = [
  { id: "note-1", type: "note", text: "ADD A LOVE INTEREST AND HAVE THEM DIE / WE WANT THIS TO WIN AN OSCAR" },
  { id: "note-2", type: "note", text: "LET'S ADD SOME SEXY ROBOTS" },
  { id: "note-3", type: "note", text: "CAN WE KILL OFF THE MAIN CHARACTER IN A SURPRISE TWIST / IT WORKED ON GAME OF THRONES" },
  { id: "note-4", type: "note", text: "WE WANT TO STAY WITH THE TRENDS, SO CAN YOU MAKE THIS MOVIE SORT OF A CROSS BETWEEN ____ AND ____? / CHOOSE TWO PREVIOUSLY PITCHED MOVIES" },
  { id: "note-5", type: "note", text: "CAN WE DO THIS MOVIE WITH PUPPETS / ACTORS MAKE ME NERVOUS" },
  { id: "note-6", type: "note", text: "I LIKE THIS IDEA BUT I WANT TO BE IN IT / MAKE ME THE MAIN CHARACTER" },
  { id: "note-7", type: "note", text: "WHAT IF THEY'VE BEEN A GHOST THE WHOLE TIME" },
  { id: "note-8", type: "note", text: "WHAT IF THE MAIN CHARACTER NEEDED TO OVERCOME THEIR FEAR OF BEES TO SAVE THE DAY" },
  { id: "note-9", type: "note", text: "MY NIECE WOULD BE PERFECT FOR THE LEAD ROLE / SHE'S 8 YEARS OLD" },
  { id: "note-10", type: "note", text: "I THINK IT IS MISSING SOMETHING / HOW ABOUT ____", draws: [{ deck: "plot", count: 1 }] },
  { id: "note-11", type: "note", text: "WHAT IF ALL THE CHARACTERS WERE IN HIGH SCHOOL" },
  { id: "note-12", type: "note", text: "PEOPLE LOVE POKEMON / HOW DO WE MAKE THIS MORE LIKE POKEMON WITHOUT GETTING SUED" },
  { id: "note-13", type: "note", text: "GREAT NEWS! / WE HAVE A GRANT TO FILM THIS WHOLE MOVIE AT THE NORTH POLE" },
  { id: "note-14", type: "note", text: "WHAT IF ALL THE CHARACTERS WORKED IN THE CIRCUS?" },
  { id: "note-15", type: "note", text: "I THINK IT'S MISSING SOMETHING / HOW ABOUT WE ADD ____?", draws: [{ deck: "plot", count: 1 }] },
  { id: "note-16", type: "note", text: "CAN THIS WHOLE MOVIE TAKE PLACE AT SUNSET? / WE WANT THIS TO WIN AT CANNES" },
  { id: "note-17", type: "note", text: "WHAT IF WE ADD A CREEPY MONSTER HUNTING OUR MAIN CHARACTERS?" },
  { id: "note-18", type: "note", text: "WHAT IF THE MAIN CHARACTER WAS JUST IN ONE OF THOSE \"VIRAL VIDEOS\"? / HOW COULD YOU WORK THAT INTO THE PLOT" },
  { id: "note-19", type: "note", text: "WHAT IF THE MAIN CHARACTER WAS ACTUALLY UNDER RUSSIAN HYPNOSIS? / COOL TWIST RIGHT?" },
  { id: "note-20", type: "note", text: "WHAT IF THE MAIN CHARACTER WAS ACTUALLY A GIANT MISUNDERSTOOD GORILLA?" },
  { id: "note-21", type: "note", text: "CAN YOU GIVE ALL THE CHARACTERS SUPERPOWERS?" },
  { id: "note-22", type: "note", text: "WHAT IF THE MAIN CHARACTER'S BEST FRIEND IS SECRETLY ... GOD!" },
  { id: "note-23", type: "note", text: "YOU KNOW WHAT EVERYONE LOVES? / DOLPHINS. / HOW CAN WE GET DOLPHINS IN THIS MOVIE?" },
  { id: "note-24", type: "note", text: "WE WANT THIS MOVIE TO APPEAL TO STONERS. / HOW WILL YOU MAKE THIS HAPPEN?" },
  { id: "note-25", type: "note", text: "PERFECT! / ONLY MAKE IT A MUSICAL WHERE EVERYONE IS PREGNANT" },
  { id: "note-26", type: "note", text: "THIS ISN'T QUITE WORKING ... LET'S REPLACE THE MAIN CHARACTER WITH ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "note-27", type: "note", text: "LET'S CAST A STAR AND HAVE THEM DIE IN THE FIRST ACT!" },
  { id: "note-28", type: "note", text: "LET'S MAKE THIS A HIP-HOP MUSICAL JUST LIKE HAMILTON! / EVERYONE LOVES HAMILTON!" },
  { id: "note-29", type: "note", text: "WHAT IF THE MAIN CHARACTER WAS A KID WHOSE PARENTS JUST DIED? / PEOPLE LOVE THAT." },
  { id: "note-30", type: "note", text: "WE NEED TO CAST DONALD TRUMP AS THE PROTAGONIST. / SORRY." },
  { id: "note-31", type: "note", text: "GREAT, BUT WE REALLY WANT THIS TO APPEAL TO FAMILIES WITH YOUNG KIDS." },
  { id: "note-32", type: "note", text: "CAN WE MAKE THIS WHOLE STORY TAKE PLACE IN ONE ROOM? / WE DON'T HAVE ANY MONEY TO SPEND ON LOCATIONS" },
  { id: "note-33", type: "note", text: "WHAT IF THE MAIN CHARACTER'S BEST FRIEND WAS A MYSTERIOUS ROBOT BUTLER?" },
  { id: "note-34", type: "note", text: "WE NEED A STEAMY ROMANCE SCENE EVERY 10 MINUTES. / KEEP IT RATED PG-13 THOUGH." },
  { id: "note-35", type: "note", text: "WHO WOULD YOU HAVE VOICE THE TALKING DOG? / ALSO ADD A TALKING DOG." },
  { id: "note-36", type: "note", text: "I'VE GOT TO BE HONEST WITH YOU. / I DON'T THINK THERE ARE ENOUGH BEARS IN THIS MOVIE." },
  { id: "note-37", type: "note", text: "YOU KNOW WHAT'S HOT RIGHT NOW? / TEEN PREGNANCY / CAN WE WORK ONE OF THOSE IN SOMEHOW" },
  { id: "note-38", type: "note", text: "WHAT IF THE MAIN CHARACTER IS LITERALLY A FISH OUT OF WATER? / LIKE IN THOSE NEMO MOVIES" },
  { id: "note-39", type: "note", text: "WHAT IF WE REPLACE THE CLIMAX OF THE MOVIE WITH A DRUM SOLO?" },
  { id: "note-40", type: "note", text: "WHAT IF WE SET THIS IN A FUTURE WHERE DIP'N'DOTS IS THE WORLD'S MOST VALUABLE RESOURCE? / WE HAVE A DEAL WITH DIP'N'DOTS" },
  { id: "note-41", type: "note", text: "WHAT IF THIS WHOLE STORY TOOK PLACE AT A PAPER SUPPLY COMPANY?" },
  { id: "note-42", type: "note", text: "WHAT IF WE REPLACE THE LOVE INTEREST WITH OBAMA? / WE HEAR HE'S LOOKING TO ACT." },
  { id: "note-43", type: "note", text: "LET'S MAKE ALL OF THE CHARACTERS MIDDLE-AGED WHITE MEN. / THAT'S AN UNDER-SERVED DEMOGRAPHIC." },
  { id: "note-44", type: "note", text: "WE'RE AIMING FOR THE NC-17 AUDIENCE WITH THIS ONE." },
  { id: "note-45", type: "note", text: "WHAT IF WE ADD AN INVISIBLE TALKING PENGUIN THAT ONLY THE MAIN CHARACTER CAN SEE?" },
  { id: "note-46", type: "note", text: "PEOPLE LOVE SHARK WEEK! / LET'S ADD SOME MORE SHARKS!" },
  { id: "note-47", type: "note", text: "CRAZY IDEA ... / WE WANT TO CAST A HOLOGRAM OF ELVIS AS THE LEAD." },
  { id: "note-48", type: "note", text: "WHAT IF THE WHOLE PLOT WAS CENTERED AROUND A HUGE CHESS TOURNAMENT?" },
  { id: "note-49", type: "note", text: "THIS DOESN'T FEEL \"DOPE\" ENOUGH. / HOW CAN WE ADD MORE \"URBAN CULTURE\"?" },
  { id: "note-50", type: "note", text: "HOW CAN WE MAKE FIDGET SPINNERS CENTRAL TO THE PLOT?" },
  { id: "note-51", type: "note", text: "WE NEED TO KEEP THIS MOVIE RATED G. / IS THAT GOING TO BE A PROBLEM?" },
  { id: "note-52", type: "note", text: "COOL. BUT WE WANT THIS TO BE THE PERFECT ____ MOVIE. / (PICK A HOLIDAY)" },
  { id: "note-53", type: "note", text: "LET'S ADD AT LEAST ONE EXPLOSION IN EVERY SCENE." },
  { id: "note-54", type: "note", text: "BUT WHAT IF WE CAST ____ AS THE LOVE INTEREST? / (NAME AN ACTOR/ACTRESS)" },
  { id: "note-55", type: "note", text: "THE PROTAGONIST NEEDS TO HAVE 10 CATS. / CATS ARE HOT RIGHT NOW." },
  { id: "note-56", type: "note", text: "WHAT IF THIS WHOLE STORY WAS SET IN AN ESCAPE ROOM?" },
  { id: "note-57", type: "note", text: "LET'S MAKE THIS A WWII MOVIE." },
  { id: "note-58", type: "note", text: "I THINK IT NEEDS LIKE THREE MORE CAR CHASES." },
  { id: "note-59", type: "note", text: "WHAT IF WE TELL THE STORY BACKWARDS? / WE WANT THIS TO WIN AT SUNDANCE." },
  { id: "note-60", type: "note", text: "THIS IS COOL BUT IT SEEMS A LITTLE UNREALISTIC, HOW CAN WE KEEP IT GROUNDED?" },
  { id: "note-61", type: "note", text: "WE HAVE ONLY ENOUGH IN THE BUDGET FOR ONE ACTOR. / IS THAT GOING TO BE A PROBLEM?" },
  { id: "note-62", type: "note", text: "LET'S SET THIS IN CANCUN. / I NEED A VACATION" },
  { id: "note-63", type: "note", text: "WHAT IF THE MAIN CHARACTER HAS A SECRET PET DRAGON?" },
  { id: "note-64", type: "note", text: "WE THINK THESE NEED TO HAVE MORE ZOMBIES. / ADD MORE ZOMBIES PLEASE." },
  { id: "note-65", type: "note", text: "WHAT IF WE ADDED A MONSTER TRYING TO KILL THE MAIN CHARACTERS IN THEIR DREAMS!" },
  { id: "note-66", type: "note", text: "WHAT IF THE MAIN CHARACTER HAD A NUCLEAR BOMB STRAPPED TO THEM? / THAT WOULD BE EXCITING, RIGHT?" },
  { id: "note-67", type: "note", text: "WHAT IF THE MAIN CHARACTER WAS JUST ADOPTED BY A SINISTER MILLIONAIRE?" },
  { id: "note-68", type: "note", text: "CAN YOU ADD A BUNCH OF SUPER ADORABLE SIDEKICKS? / LIKE THOSE LITTLE YELLOW MINION GUYS." },
  { id: "note-69", type: "note", text: "CAN WE MAKE THIS A SEQUEL TO ____? / CHOOSE ANOTHER PREVIOUSLY PITCHED MOVIE." },
  { id: "note-70", type: "note", text: "LET'S ADD A CRAZY HELICOPTER CHASE RIGHT AT THE START OF THE MOVIE!" },
  { id: "note-71", type: "note", text: "CAN YOU MAKE THE LOVE INTEREST A SUPER CREEPY MONSTER? / THOSE PLAY WELL IN OCTOBER." },
  { id: "note-72", type: "note", text: "CAN WE ADD SOME EDGY RACIAL TENSION? THAT'S IN THE ZEITGEIST RIGHT NOW." },
  { id: "note-73", type: "note", text: "WHAT IF THIS WAS A GRITTY REBOOT OF ____? / CHOOSE ANOTHER PLAYER'S MOVIE." },
  { id: "note-74", type: "note", text: "WHAT IF THE MAIN CHARACTER WAS A ROBOT THAT COULD TRANSFORM INTO A CAR?" },
  { id: "note-75", type: "note", text: "CAN WE DO HALF OF THIS MOVIE IN CLAYMATION?" },
  { id: "note-76", type: "note", text: "WE NEED MORE '80S POP CULTURE REFERENCES. / NOSTALGIA IS SUPER HOT RIGHT NOW." },
  { id: "note-77", type: "note", text: "LET'S SET THIS DURING THE CIVIL WAR. / COOL?" },
  { id: "note-78", type: "note", text: "SOUNDS GOOD. BUT CAN WE ADD SOME MORE TIME TRAVEL?" },
  { id: "note-79", type: "note", text: "WHAT IF THE MAIN CHARACTER WAS A ROBOT ... / BUT THEY DIDN'T KNOW THEY WERE A ROBOT!" },
  { id: "note-80", type: "note", text: "OUR FOREIGN MARKET LOVES ACTION AND HORROR, HOW CAN YOU ADD MORE OF BOTH?" },
  { id: "note-81", type: "note", text: "CAN WE SET THIS DURING THE WAR IN IRAQ?" },
  { id: "note-82", type: "note", text: "WHAT IF EVERY CHARACTER WAS A HITMAN?" },
  { id: "note-83", type: "note", text: "WHAT IF THE MAIN CHARACTER COULD TALK TO ANIMALS? / BUT HAD TO KEEP IT A SECRET!" },
  { id: "note-84", type: "note", text: "WHAT IF THEY WERE BOTH SECRET AGENTS ... / BUT THEY DIDN'T KNOW THEY WERE BOTH SECRET AGENTS!" },
  { id: "note-85", type: "note", text: "DO YOU THINK WE CAN REPLACE EVERY CONFLICT WITH A DANCE-OFF?" },
  { id: "note-86", type: "note", text: "CAN WE ADD ONE MORE PIRANHA SWARM?" },
  { id: "note-87", type: "note", text: "HONESTLY I THINK IT IS TOO FUNNY. / CAN YOU TRY A MORE SERIOUS TAKE?" },
  { id: "note-88", type: "note", text: "LET'S ADD A SUPER EVIL ____ AS A VILLAIN. / (DRAW A RANDOM CHARACTER CARD)", draws: [{ deck: "character", count: 1 }] },
  { id: "note-89", type: "note", text: "WHAT IF WE SET THIS BACK IN BIBLICAL TIMES?" },
  { id: "note-90", type: "note", text: "HOW CAN WE MAKE THIS THE NEXT BIG PIRATE FRANCHISE?" },
  { id: "note-91", type: "note", text: "WE WANT TO MAKE THIS A MUSICAL. / ALL THE CHARACTERS NEED TO SING." },
  { id: "note-92", type: "note", text: "ADD SOME DRAGONS AND ICE ZOMBIES. / PEOPLE GO CRAZY FOR THAT STUFF!" },
  { id: "note-93", type: "note", text: "WHAT IF THE MAIN CHARACTER WAS A DASHING AND HANDSOME STUDIO EXECUTIVE?" },
  { id: "note-94", type: "note", text: "WHAT IF THE MAIN CHARACTER'S SUPERPOWER WAS TALKING TO CATS?" },
  { id: "note-95", type: "note", text: "WHAT IF THIS TOOK PLACE IN A POST-APOCALYPTIC WASTELAND?" },
  { id: "note-96", type: "note", text: "WE LOVE THAT ____ DID IN THAT MOVIE, CAN YOU MAKE THIS MOVIE MORE LIKE THEIRS? / CHOOSE A PLAYER'S PREVIOUSLY PITCHED MOVIE." },
  { id: "note-97", type: "note", text: "WHAT IF ALL THE CHARACTERS ARE PLAYED BY ANIMATED FRUITS AND VEGETABLES?" },
  { id: "note-98", type: "note", text: "WHAT IF WE SET THIS STORY ON THE FIRST HUMAN COLONY ON MARS?" },
  { id: "note-99", type: "note", text: "LOVE IT. / BUT WHAT IF WE ADD SOME CRAZY SLAPSTICK COMEDY?" },
  { id: "note-100", type: "note", text: "SOOOO ... WE ONLY HAVE $1000 SPECIAL EFFECTS BUDGET. / HOW CAN YOU MAKE THAT WORK?" },
  { id: "note-101", type: "note", text: "WE LOVE IT, BUT WHAT IF WE ACTUALLY SPLIT THIS MOVIE INTO THREE MOVIES? / WHAT WOULD PART THREE LOOK LIKE?" },
  { id: "note-102", type: "note", text: "WHAT IF WE ADD 100 ASSASSINS TRYING TO KILL OUR MAIN CHARACTERS?" },
  { id: "note-103", type: "note", text: "LET'S DO THIS WHOLE THING WITHOUT DIALOGUE. / THAT'D BE ARTSY!" },
  { id: "note-104", type: "note", text: "GREAT, BUT WE NEED THIS MOVIE TO HAVE A POSITIVE MESSAGE ABOUT CYBERBULLYING." },
  { id: "note-105", type: "note", text: "WHAT IF THE MAIN CHARACTER GOT THEIR SUPERPOWERS FROM ____? / CHOOSE A CORPORATE SPONSOR" },
  { id: "note-106", type: "note", text: "WHAT IF THIS WAS ACTUALLY A KID-FRIENDLY SPIN-OFF TO ____? / CHOOSE ANOTHER PREVIOUSLY PITCHED MOVIE" },
  { id: "note-107", type: "note", text: "WHAT IF WE SET THIS DURING MEDIEVAL TIMES INSTEAD?" },
  { id: "note-108", type: "note", text: "WHAT IF THE MAIN CHARACTER HAS TO RESCUE A KIDNAPPED PRINCE?" },
  { id: "note-109", type: "note", text: "LET'S SET THIS ON THE MOON!" },
  { id: "note-110", type: "note", text: "I THINK THIS NEEDS MORE ALIENS. / BUT NOT DUMB ALIENS ... / COOL ALIENS ... / YOU KNOW?" },
  { id: "note-111", type: "note", text: "WHAT IF ALL OF THE CHARACTERS WERE TRAPPED IN A BLIZZARD?" },
  { id: "note-112", type: "note", text: "WE WANT TO TRY SOMETHING CRAZY. EVERY CHARACTER IS GOING TO BE PLAYED BY ____. / (PICK AN ACTOR/ACTRESS)" },
  { id: "note-113", type: "note", text: "HOW CAN WE CHANGE THE THEME OF THIS MOVIE TO BE, \"YOU NEED TO BUY MORE THINGS TO BE HAPPY\"." },
  { id: "note-114", type: "note", text: "SET IT IN SPACE, ADD A BUNCH OF LASER SWORDS. / WHAT WOULD THAT LOOK LIKE?" },
  { id: "note-115", type: "note", text: "WHAT IF THIS WERE A WESTERN? / THOSE ARE HIP NOW, RIGHT?" },
  { id: "note-116", type: "note", text: "WHAT IF EVERYTHING YOU JUST SAID WAS ACTUALLY THE SETUP TO AN ELABORATE HEIST?" },
  { id: "note-117", type: "note", text: "LOVE IT, BUT WE WANT THIS TO BE A CROSSOVER EVENT WITH ____. / CHOOSE A PREVIOUSLY PITCHED MOVIE." },
  { id: "note-118", type: "note", text: "LET'S ADD SOME CANCER, BUT DON'T MAKE IT A BIG DEAL. / WE DON'T WANT THIS TO BE A DOWNER." },
  { id: "note-119", type: "note", text: "CRAZY IDEA, WHAT IF THIS WHOLE CAST WAS A BUNCH OF TALKING HOUSE PETS?" },
  { id: "note-120", type: "note", text: "I THINK THIS COULD REALLY USE AN ALIEN INVASION IN ACT THREE." },
  { id: "note-121", type: "note", text: "ADD A REALLY HOT LOVE INTEREST. / WE WANT THIS TO BE THE PERFECT DATE NIGHT MOVIE." },
  { id: "note-122", type: "note", text: "WHAT IF THEY WERE ON A SUPERHERO TEAM WITH ____ AND ____?", draws: [{ deck: "character", count: 2 }] },
  { id: "note-123", type: "note", text: "WHAT IF ALL OF THIS WAS TAKING PLACE IN A DREAM?" },
  { id: "note-124", type: "note", text: "COOL, BUT WHAT IF THE VILLAIN WAS ACTUALLY JUST ____ IN DISGUISE?", draws: [{ deck: "character", count: 1 }] },
  { id: "note-125", type: "note", text: "HOW CAN WE TIE THIS IN WITH THE HARRY POTTER FRANCHISE?" },
  { id: "note-126", type: "note", text: "CRAZY THOUGHT. LET'S SET THIS WHOLE THING ON THE INTERNATIONAL SPACE STATION." },
  { id: "note-127", type: "note", text: "WHAT IF THE MAIN CHARACTER USED A SAMSUNG GALAXY TO SAVE THE DAY. / WE HAVE A DEAL WITH SAMSUNG." },
  { id: "note-128", type: "note", text: "CRAZY IDEA. LET'S ADD ____ AS A LOVE INTEREST.", draws: [{ deck: "character", count: 1 }] },
  { id: "note-129", type: "note", text: "HOLD ON, I HAVE SO MANY IDEAS FOR THIS ONE! / (DRAW AND PLAY TWO RANDOM NOTE CARDS)", draws: [{ deck: "note", count: 2 }] },
  { id: "note-130", type: "note", text: "OBESITY IS HUGE THESE DAYS. / CAN WE MAKE HEALTHY EATING CENTRAL TO THE PLOT?" },
  { id: "note-131", type: "note", text: "WHAT IF ALL THE CHARACTERS WERE VIKINGS? / VIKINGS ARE COOL!" },
  { id: "note-132", type: "note", text: "WHAT IF THIS WAS THE SECRET TRUE STORY OF THE LOCH NESS MONSTER?" },
  { id: "note-133", type: "note", text: "WE HAVE A DEAL WITH PIZZA HUT. / SO HOW CAN WE MAKE THIS ABOUT PIZZA SAVING THE DAY?" },
  { id: "note-134", type: "note", text: "WHAT IF THE HERO WAS ACTUALLY TRYING TO ESCAPE A BLOOD-THIRSTY CULT?" },
  { id: "note-135", type: "note", text: "LET'S MAKE THE MAIN CHARACTER A LIZARD-PERSON DISGUISED AS A HUMAN." },
  { id: "note-136", type: "note", text: "BUT WHAT IF THIS WERE SET IN A DYSTOPIAN FUTURE WHERE KIDS FIGHT TO THE DEATH ON A REALITY TV SHOW?" },
  { id: "note-137", type: "note", text: "HEAR ME OUT, I THINK THIS NEEDS MORE MEMES. / KIDS LOVE MEMES!" },
  { id: "note-138", type: "note", text: "BUT WHAT IF WE ADD A PRISON BREAK ON PAGE 15?" },
  { id: "note-139", type: "note", text: "TWO WORDS, LASER DOGS!" },
  { id: "note-140", type: "note", text: "BUT WHAT IF THIS ALL TOOK PLACE DURING A GIANT MONSTER ATTACK?" },
  { id: "note-141", type: "note", text: "LOVE IT, NOW LET'S WORK ON THE SEQUEL." },
  { id: "note-142", type: "note", text: "WHAT IF ALL THE CHARACTERS WERE FRESHMEN IN COLLEGE?" },
  { id: "note-143", type: "note", text: "WE LOVE IT, BUT WHAT IF WE ACTUALLY SPLIT THIS MOVIE INTO THREE MOVIES? / WHAT WOULD PART ONE LOOK LIKE?" },
  { id: "note-144", type: "note", text: "WE LOVE IT, BUT WHAT IF WE ACTUALLY SPLIT THIS MOVIE INTO THREE MOVIES? / WHAT WOULD PART TWO LOOK LIKE?" },
  { id: "note-145", type: "note", text: "HOW CAN WE TURN THIS INTO THE NEXT GODZILLA REBOOT?" },
  { id: "note-146", type: "note", text: "LET'S REPLACE ALL THE VILLAINS WITH COWS? / WE HAVE A DEAL WITH CHICK-FIL-A." },
  { id: "note-147", type: "note", text: "WE REALLY WANT MORE PLOT TWISTS HERE ... / LIKE ONE EVERY 10 MINUTES AT LEAST." },
  { id: "note-148", type: "note", text: "WHAT IF THE OPENING SCENE WAS THE INVASION ON D-DAY?" },
  { id: "note-149", type: "note", text: "CAN WE ADD AT LEAST ONE DINOSAUR?" },
  { id: "note-150", type: "note", text: "THIS IS GREAT, BUT WHAT IF EVERYTHING YOU'VE SAID SO FAR WAS JUST A FLASHBACK BEFORE THE MAIN STORY?" },
  { id: "note-151", type: "note", text: "I THINK WE NEED MORE TORNADOES IN THIS MOVIE." },
  { id: "note-152", type: "note", text: "WE WANT THIS MOVIE TO BE SUPER SMART. / SO LIKE ... / ADD SOME MATH OR SOMETHING." },
  { id: "note-153", type: "note", text: "WHAT IF THE HERO WERE THE CAPTAIN OF AN INTERSTELLAR SPACE SHIP?" },
  { id: "note-154", type: "note", text: "CAN WE MAKE THIS BASED OFF OF TRUE EVENTS?" },
  { id: "note-155", type: "note", text: "GREAT, BUT WHAT IF THE WHOLE THING WAS SET ON AN AIRPLANE?" },
  { id: "note-156", type: "note", text: "LET'S SET THE WHOLE STORY IN A HOT TUB." },
  { id: "note-157", type: "note", text: "WHAT'S THE COOLEST THING IN THIS MOVIE THAT WE COULD SEE AS A TOY? / GREAT! NOW PUT THAT IN EVERY SCENE." },
  { id: "note-158", type: "note", text: "WE WANT SOME REALLY COOL 3D SCENES FOR THIS. / WHAT CAN WE MAKE POP OUT AT THE CROWD?" },
  { id: "note-159", type: "note", text: "HONESTLY, WE'RE MAKING THIS FOR LATE-NIGHT TV. / WE JUST WANT THIS MOVIE TO PUT PEOPLE TO SLEEP." },
  { id: "note-160", type: "note", text: "WE LOVED THAT AVENGERS MOVIE SO WE WANT TO TURN THIS INTO A BIG CROSSOVER WITH ____. / CHOOSE A POPULAR FRANCHISE" },
  { id: "note-161", type: "note", text: "WHAT IF THE WHOLE UNIVERSE WERE IN DANGER? / CAN YOU ADD THAT TO THE VILLAIN'S PLAN." },
  { id: "note-162", type: "note", text: "ADD MORE DADS, WE WANT THIS TO BE THE PERFECT FATHER'S DAY MOVIE." },
  { id: "note-163", type: "note", text: "WHAT IF WE SET THIS WHOLE MOVIE IN AN ELEVATOR?" },
  { id: "note-164", type: "note", text: "CAN WE ADD A BUNCH OF HORNY TEENS THAT GET KILLED OFF THROUGHOUT THE MOVIE?" },
  { id: "note-165", type: "note", text: "WHAT IF THE WHOLE PLOT WERE CENTERED AROUND A CHEERLEADING COMPETITION?" },
  { id: "note-166", type: "note", text: "WHAT IF THE MAIN CHARACTER HAD TWELVE KIDS?" },
];

export function getSeedCards(): { plot: Card[]; character: Card[]; note: Card[] } {
  return { plot: PLOT_CARDS, character: CHARACTER_CARDS, note: NOTE_CARDS };
}