import type { Card } from "@pitch-storm/shared";

const PLOT_CARDS: Card[] = [
  { id: "plot-1", type: "plot", text: "gets in big trouble with the mafia." },
  { id: "plot-2", type: "plot", text: "joins the army to save their aging father in medieval China." },
  { id: "plot-3", type: "plot", text: "tries to take down the top flute player in the band." },
  { id: "plot-4", type: "plot", text: "travels through time to save the world." },
  { id: "plot-5", type: "plot", text: "battles a swarm of radioactive mutants." },
  { id: "plot-6", type: "plot", text: "tries to break the record for baking the worlds largest pizza." },
  { id: "plot-7", type: "plot", text: "accidentally starts WWIII." },
  { id: "plot-8", type: "plot", text: "fights a gang of bullies at school." },
  { id: "plot-9", type: "plot", text: "hunts for bigfoot." },
  { id: "plot-10", type: "plot", text: "must stop a child mayor from bankrupting their hometown." },
  { id: "plot-11", type: "plot", text: "competes in fast and furious illegal street racing." },
  { id: "plot-12", type: "plot", text: "becomes trapped in a dangerous video game." },
  { id: "plot-13", type: "plot", text: "tries to solve a mystery deep under the Pacific Ocean." },
  { id: "plot-14", type: "plot", text: "discovers a terrible secret about their own family." },
  { id: "plot-15", type: "plot", text: "goes on the run in New Zealand bush country." },
  { id: "plot-16", type: "plot", text: "incites a rebellion in an oppressed insane asylum." },
  { id: "plot-17", type: "plot", text: "tries to escape from hell." },
  { id: "plot-18", type: "plot", text: "battles addiction to prescription drugs." },
  { id: "plot-19", type: "plot", text: "makes a deal with the devil." },
  { id: "plot-20", type: "plot", text: "competes in a deadly reality TV competition." },
  { id: "plot-21", type: "plot", text: "tries to save as many people as possible from Nazis in WWII." },
  { id: "plot-22", type: "plot", text: "goes on a terrible drug trip during a family reunion." },
  { id: "plot-23", type: "plot", text: "struggles to adjust to civilian life after returning from the war." },
  { id: "plot-24", type: "plot", text: "crashes their plane in the Canadian wilderness." },
  { id: "plot-25", type: "plot", text: "must transport a dangerous criminal across a war-torn city." },
  { id: "plot-26", type: "plot", text: "struggles to raise a family in the Wild West." },
  { id: "plot-27", type: "plot", text: "goes undercover in the world of hip-hop culture." },
  { id: "plot-28", type: "plot", text: "tries to save the world from zombie apocalypse." },
  { id: "plot-29", type: "plot", text: "in an awkward teenage romance." },
  { id: "plot-30", type: "plot", text: "tries to stop a ferry boat from sinking." },
  { id: "plot-31", type: "plot", text: "invents a gadget that will change the world." },
  { id: "plot-32", type: "plot", text: "robs a bank to get themselves out of debt." },
  { id: "plot-33", type: "plot", text: "throws the greatest house party ever!" },
  { id: "plot-34", type: "plot", text: "throws a bachelor/ette party that goes terribly wrong." },
  { id: "plot-35", type: "plot", text: "is mistakenly sent to heaven." },
  { id: "plot-36", type: "plot", text: "leads a deadly rescue mission on Mt. Everest." },
  { id: "plot-37", type: "plot", text: "gets kidnapped by malevolent sock puppets." },
  { id: "plot-38", type: "plot", text: "races around the world in a hot air balloon." },
  { id: "plot-39", type: "plot", text: "explores a dangerous alien planet." },
  { id: "plot-40", type: "plot", text: "tries to escape an island full of hungry dinosaurs." },
  { id: "plot-41", type: "plot", text: "seeks their fortune during the Alaskan Gold Rush." },
  { id: "plot-42", type: "plot", text: "has a steamy affair with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-43", type: "plot", text: "teaches poor kids to read." },
  { id: "plot-44", type: "plot", text: "falls for a dangerous femme fatale." },
  { id: "plot-45", type: "plot", text: "tries to disarm a series of devilish traps." },
  { id: "plot-46", type: "plot", text: "embarks on the first human colonization mission to another galaxy." },
  { id: "plot-47", type: "plot", text: "gets lost in the Amazon jungle." },
  { id: "plot-48", type: "plot", text: "must finish a dangerous supernatural board game to survive." },
  { id: "plot-49", type: "plot", text: "searches for enlightenment in the far corners of the earth." },
  { id: "plot-50", type: "plot", text: "is the only witness to a mafia killing." },
  { id: "plot-51", type: "plot", text: "pilots a giant robot to save the world from monsters." },
  { id: "plot-52", type: "plot", text: "goes undercover as a flamenco dancer to hide from the mob." },
  { id: "plot-53", type: "plot", text: "tries to save their family from kidnappers." },
  { id: "plot-54", type: "plot", text: "struggles with the bleak reality of life in the big city." },
  { id: "plot-55", type: "plot", text: "races to stop the detonation of a biological weapon in New York City." },
  { id: "plot-56", type: "plot", text: "leads a rebellion against a totalitarian regime." },
  { id: "plot-57", type: "plot", text: "trapped on Mt. Everest during a deadly storm." },
  { id: "plot-58", type: "plot", text: "will do anything for fame on a reality TV show." },
  { id: "plot-59", type: "plot", text: "discovers a hidden island full of mythical creatures." },
  { id: "plot-60", type: "plot", text: "tries to scam their way to fame in Hollywood." },
  { id: "plot-61", type: "plot", text: "hosts the worlds worst houseguest." },
  { id: "plot-62", type: "plot", text: "makes contact with dangerous aliens." },
  { id: "plot-63", type: "plot", text: "goes on a quest to slay a dragon." },
  { id: "plot-64", type: "plot", text: "hunts for elves in a mysterious forest." },
  { id: "plot-65", type: "plot", text: "goes on the run to escape deadly assassins." },
  { id: "plot-66", type: "plot", text: "searches for the cure of a deadly plague." },
  { id: "plot-67", type: "plot", text: "hunts and is hunted by a deadly serial killer." },
  { id: "plot-68", type: "plot", text: "is kidnapped by terrorists!" },
  { id: "plot-69", type: "plot", text: "is accidentally elected president of the United States." },
  { id: "plot-70", type: "plot", text: "treks across a dangerous desert to save their friends." },
  { id: "plot-71", type: "plot", text: "gets trapped in the body of a bear." },
  { id: "plot-72", type: "plot", text: "embarks on an epic journey to destroy an evil magical artifact." },
  { id: "plot-73", type: "plot", text: "only has one month to complete their bucket list." },
  { id: "plot-74", type: "plot", text: "competes against the rich kid team in a heartwarming underdog story." },
  { id: "plot-75", type: "plot", text: "fights to thwart an ancient and unstoppable evil." },
  { id: "plot-76", type: "plot", text: "outwits gangsters and cops in a series of death-defying car chases." },
  { id: "plot-77", type: "plot", text: "goes on a mad quest to kill the whale that ate their dog." },
  { id: "plot-78", type: "plot", text: "stranded on a lifeboat with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-79", type: "plot", text: "discovers a dangerous secret at a popular new theme park." },
  { id: "plot-80", type: "plot", text: "on a quest for a treasure that will save the kingdom." },
  { id: "plot-81", type: "plot", text: "must stop their evil twin from ruining their life!" },
  { id: "plot-82", type: "plot", text: "becomes a vigilante to rid their city of crime." },
  { id: "plot-83", type: "plot", text: "gets an exciting new job working for ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-84", type: "plot", text: "steals from the rich and gives to the poor and becomes a local legend." },
  { id: "plot-85", type: "plot", text: "attempts a desperate escape from Seaworld." },
  { id: "plot-86", type: "plot", text: "will do whatever it takes to become a world-famous chef." },
  { id: "plot-87", type: "plot", text: "fights in bloody gladiator death matches." },
  { id: "plot-88", type: "plot", text: "fights for the ultimate boxing title." },
  { id: "plot-89", type: "plot", text: "discovers the mythical city of El Dorado." },
  { id: "plot-90", type: "plot", text: "competes in a deadly underground martial arts tournament." },
  { id: "plot-91", type: "plot", text: "tries to steal the Declaration of Independence." },
  { id: "plot-92", type: "plot", text: "inherits an evil doll." },
  { id: "plot-93", type: "plot", text: "fights to stop an evil AI from destroying humanity." },
  { id: "plot-94", type: "plot", text: "faces a difficult choice between love and money." },
  { id: "plot-95", type: "plot", text: "receives an unexpected message from God." },
  { id: "plot-96", type: "plot", text: "leads the rescue mission for a missing child." },
  { id: "plot-97", type: "plot", text: "wins big at a casino and becomes the target of the mafia." },
  { id: "plot-98", type: "plot", text: "tries to capture a giant ape on a mysterious island." },
  { id: "plot-99", type: "plot", text: "fights a huge angry bear." },
  { id: "plot-100", type: "plot", text: "battles corruption in the greeting card industry." },
  { id: "plot-101", type: "plot", text: "on a deadly white-water rafting trip." },
  { id: "plot-102", type: "plot", text: "fights in a boxing match against their ultimate rival: ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-103", type: "plot", text: "building a rocketship to escape a dying planet." },
  { id: "plot-104", type: "plot", text: "accidentally joins a cult on their first day in college." },
  { id: "plot-105", type: "plot", text: "involved in a complicated love triangle." },
  { id: "plot-106", type: "plot", text: "leads a slave rebellion in ancient Rome." },
  { id: "plot-107", type: "plot", text: "fights against evil robots that look like people." },
  { id: "plot-108", type: "plot", text: "discovers the fountain of youth." },
  { id: "plot-109", type: "plot", text: "flees from a tribe of cannibals." },
  { id: "plot-110", type: "plot", text: "in a series of romantic misadventures." },
  { id: "plot-111", type: "plot", text: "falls madly in love with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-112", type: "plot", text: "discovers a map leading to a legendary treasure hoard." },
  { id: "plot-113", type: "plot", text: "on a quest to discover Atlantis." },
  { id: "plot-114", type: "plot", text: "fights to save a rare and mysterious animal from poachers." },
  { id: "plot-115", type: "plot", text: "plots to escape a retirement home in Florida." },
  { id: "plot-116", type: "plot", text: "attempts to rescue hostages from a skyscraper." },
  { id: "plot-117", type: "plot", text: "tries to steal the worlds largest diamond." },
  { id: "plot-118", type: "plot", text: "fights to take down a dangerous cult." },
  { id: "plot-119", type: "plot", text: "struggles to bring their best friend back from the dead." },
  { id: "plot-120", type: "plot", text: "competes on a cooking game show to pay for their mom's medical bills." },
  { id: "plot-121", type: "plot", text: "matches wits against a wily leprechaun." },
  { id: "plot-122", type: "plot", text: "struggles to survive after a deadly shipwreck." },
  { id: "plot-123", type: "plot", text: "gets trapped overnight in a haunted asylum." },
  { id: "plot-124", type: "plot", text: "discovers a conspiracy of lizard people in the government." },
  { id: "plot-125", type: "plot", text: "has just two hours to find a huge amount of money for a dangerous mobster." },
  { id: "plot-126", type: "plot", text: "must protect their small village from a horde of bandits." },
  { id: "plot-127", type: "plot", text: "leads a ragtag crew of pirates against the British Navy." },
  { id: "plot-128", type: "plot", text: "is abducted by aliens!" },
  { id: "plot-129", type: "plot", text: "makes a selfish wish in a demonic wishing well." },
  { id: "plot-130", type: "plot", text: "haunted by the angry ghost of ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-131", type: "plot", text: "searches for peace in a dangerous radioactive wasteland." },
  { id: "plot-132", type: "plot", text: "is stranded on a desert island." },
  { id: "plot-133", type: "plot", text: "tries to save a family of Bigfoots from a deadly wildfire." },
  { id: "plot-134", type: "plot", text: "struggles to write the next great American novel." },
  { id: "plot-135", type: "plot", text: "fights to save their family from demonic possession." },
  { id: "plot-136", type: "plot", text: "will do whatever it takes to save the local library." },
  { id: "plot-137", type: "plot", text: "struggles to rebuild their community after a devastating hurricane." },
  { id: "plot-138", type: "plot", text: "accidentally becomes the Pope." },
  { id: "plot-139", type: "plot", text: "falls in love with a merperson." },
  { id: "plot-140", type: "plot", text: "tries to escape from the sinking city of Atlantis." },
  { id: "plot-141", type: "plot", text: "becomes worshipped as gods by a primitive culture." },
  { id: "plot-142", type: "plot", text: "battles an evil possessed book in a bookstore." },
  { id: "plot-143", type: "plot", text: "trapped in a dark version of our own reality." },
  { id: "plot-144", type: "plot", text: "goes for gold in Olympic figure skating." },
  { id: "plot-145", type: "plot", text: "must win enough money at the talent show to pay for their grandma's surgery." },
  { id: "plot-146", type: "plot", text: "searches for a stolen nuclear bomb." },
  { id: "plot-147", type: "plot", text: "goes on a dangerous ocean voyage." },
  { id: "plot-148", type: "plot", text: "tries to save their small beach town from a monstrous seal." },
  { id: "plot-149", type: "plot", text: "is held hostage at a karaoke bar run by monsters." },
  { id: "plot-150", type: "plot", text: "discovers the secret world of modern wizards." },
  { id: "plot-151", type: "plot", text: "fights a supernatural killer clown." },
  { id: "plot-152", type: "plot", text: "goes on a quest for the Holy Grail." },
  { id: "plot-153", type: "plot", text: "goes back in time to kill Hitler." },
  { id: "plot-154", type: "plot", text: "protecting the world's last unicorn from an evil cosmetics company." },
  { id: "plot-155", type: "plot", text: "flees from natural disaster in a near-future apocalypse." },
  { id: "plot-156", type: "plot", text: "learns that they are heir to the throne of an ancient kingdom." },
  { id: "plot-157", type: "plot", text: "discovering the true origins of Santa Claus." },
  { id: "plot-158", type: "plot", text: "steals a magical treasure from a dangerous witch." },
  { id: "plot-159", type: "plot", text: "navigates the secret world of modern vampires." },
  { id: "plot-160", type: "plot", text: "Choose the plot of your favourite video game. Your movie is an adaptation of that plot.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-161", type: "plot", text: "Choose a plot previously pitched by another player. Your movie is a broadway adaptation of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-162", type: "plot", text: "Choose a plot previously pitched by another player. Your movie is a hilarious spoof of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-163", type: "plot", text: "Choose the plot to your favourite movie. Your movie is a gritty reboot of that idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-164", type: "plot", text: "Choose the plot to your favourite book. Your movie is an adaptation of that book.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-165", type: "plot", text: "Choose a plot previously pitched. Your movie is a gritty reboot of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-166", type: "plot", text: "Choose the plot of your favourite movie. This is another sequel to that movie.", header: "FRANCHISE PITCH:", isFranchise: true },
];

const CHARACTER_CARDS: Card[] = [
  { id: "char-1", type: "character", text: "A retired villain who runs a bakery" },
  { id: "char-2", type: "character", text: "A detective who is secretly three raccoons in a trench coat" },
  { id: "char-3", type: "character", text: "A grandmother who was a spy in the 1970s" },
  { id: "char-4", type: "character", text: "A lighthouse keeper who talks to the sea" },
  { id: "char-5", type: "character", text: "A child who can see 5 minutes into the future" },
  { id: "char-6", type: "character", text: "A robot butler who has developed a passion for jazz" },
  { id: "char-7", type: "character", text: "A wizard who has forgotten every spell except one" },
  { id: "char-8", type: "character", text: "A mail carrier who delivers letters between dimensions" },
  { id: "char-9", type: "character", text: "A museum night guard who befriends the exhibits" },
  { id: "char-10", type: "character", text: "A fortune teller who is always wrong but in a helpful way" },
];

const NOTE_CARDS: Card[] = [
  { id: "note-1", type: "note", text: "Add a musical number" },
  { id: "note-2", type: "note", text: "The lead actor must cry for real" },
  { id: "note-3", type: "note", text: "Include a 5-minute car chase" },
  { id: "note-4", type: "note", text: "The villain must be the hero's own reflection" },
  { id: "note-5", type: "note", text: "Everyone in the movie must speak in rhyme" },
  { id: "note-6", type: "note", text: "Add a flashback to a flashback" },
  { id: "note-7", type: "note", text: "The movie must end on a cliffhanger" },
  { id: "note-8", type: "note", text: "Add a CGI talking animal sidekick" },
  { id: "note-9", type: "note", text: "The soundtrack must be entirely kazoos" },
  { id: "note-10", type: "note", text: "Halfway through, the movie must switch genres" },
];

export function getSeedCards(): { plot: Card[]; character: Card[]; note: Card[] } {
  return { plot: PLOT_CARDS, character: CHARACTER_CARDS, note: NOTE_CARDS };
}