import type { Card } from "@pitch-storm/shared";

const PLOT_CARDS: Card[] = [
  { id: "plot-1", type: "plot", text: "gets in big trouble with the mafia." },
  { id: "plot-2", type: "plot", text: "joins the army to save their aging father in medieval China." },
  { id: "plot-3", type: "plot", text: "tries to take down the top flute player in the band." },
  { id: "plot-4", type: "plot", text: "travels through time to save the world." },
  { id: "plot-5", type: "plot", text: "battles a swarm of radioactive mutants." },
  { id: "plot-6", type: "plot", text: "tries to break the record for baking the worlds largest pizza." },
  { id: "plot-7", type: "plot", text: "accidentally starts WWIII." },
  { id: "plot-8", type: "plot", text: "fights a gang of bullies at school." },
  { id: "plot-9", type: "plot", text: "hunts for bigfoot." },
  { id: "plot-10", type: "plot", text: "must stop a child mayor from bankrupting their hometown." },
  { id: "plot-11", type: "plot", text: "competes in fast and furious illegal street racing." },
  { id: "plot-12", type: "plot", text: "becomes trapped in a dangerous video game." },
  { id: "plot-13", type: "plot", text: "tries to solve a mystery deep under the Pacific Ocean." },
  { id: "plot-14", type: "plot", text: "discovers a terrible secret about their own family." },
  { id: "plot-15", type: "plot", text: "goes on the run in New Zealand bush country." },
  { id: "plot-16", type: "plot", text: "incites a rebellion in an oppressed insane asylum." },
  { id: "plot-17", type: "plot", text: "tries to escape from hell." },
  { id: "plot-18", type: "plot", text: "battles addiction to prescription drugs." },
  { id: "plot-19", type: "plot", text: "makes a deal with the devil." },
  { id: "plot-20", type: "plot", text: "competes in a deadly reality TV competition." },
  { id: "plot-21", type: "plot", text: "tries to save as many people as possible from Nazis in WWII." },
  { id: "plot-22", type: "plot", text: "goes on a terrible drug trip during a family reunion." },
  { id: "plot-23", type: "plot", text: "struggles to adjust to civilian life after returning from the war." },
  { id: "plot-24", type: "plot", text: "crashes their plane in the Canadian wilderness." },
  { id: "plot-25", type: "plot", text: "must transport a dangerous criminal across a war-torn city." },
  { id: "plot-26", type: "plot", text: "struggles to raise a family in the Wild West." },
  { id: "plot-27", type: "plot", text: "goes undercover in the world of hip-hop culture." },
  { id: "plot-28", type: "plot", text: "tries to save the world from zombie apocalypse." },
  { id: "plot-29", type: "plot", text: "in an awkward teenage romance." },
  { id: "plot-30", type: "plot", text: "tries to stop a ferry boat from sinking." },
  { id: "plot-31", type: "plot", text: "invents a gadget that will change the world." },
  { id: "plot-32", type: "plot", text: "robs a bank to get themselves out of debt." },
  { id: "plot-33", type: "plot", text: "throws the greatest house party ever!" },
  { id: "plot-34", type: "plot", text: "throws a bachelor/ette party that goes terribly wrong." },
  { id: "plot-35", type: "plot", text: "is mistakenly sent to heaven." },
  { id: "plot-36", type: "plot", text: "leads a deadly rescue mission on Mt. Everest." },
  { id: "plot-37", type: "plot", text: "gets kidnapped by malevolent sock puppets." },
  { id: "plot-38", type: "plot", text: "races around the world in a hot air balloon." },
  { id: "plot-39", type: "plot", text: "explores a dangerous alien planet." },
  { id: "plot-40", type: "plot", text: "tries to escape an island full of hungry dinosaurs." },
  { id: "plot-41", type: "plot", text: "seeks their fortune during the Alaskan Gold Rush." },
  { id: "plot-42", type: "plot", text: "has a steamy affair with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-43", type: "plot", text: "teaches poor kids to read." },
  { id: "plot-44", type: "plot", text: "falls for a dangerous femme fatale." },
  { id: "plot-45", type: "plot", text: "tries to disarm a series of devilish traps." },
  { id: "plot-46", type: "plot", text: "embarks on the first human colonization mission to another galaxy." },
  { id: "plot-47", type: "plot", text: "gets lost in the Amazon jungle." },
  { id: "plot-48", type: "plot", text: "must finish a dangerous supernatural board game to survive." },
  { id: "plot-49", type: "plot", text: "searches for enlightenment in the far corners of the earth." },
  { id: "plot-50", type: "plot", text: "is the only witness to a mafia killing." },
  { id: "plot-51", type: "plot", text: "pilots a giant robot to save the world from monsters." },
  { id: "plot-52", type: "plot", text: "goes undercover as a flamenco dancer to hide from the mob." },
  { id: "plot-53", type: "plot", text: "tries to save their family from kidnappers." },
  { id: "plot-54", type: "plot", text: "struggles with the bleak reality of life in the big city." },
  { id: "plot-55", type: "plot", text: "races to stop the detonation of a biological weapon in New York City." },
  { id: "plot-56", type: "plot", text: "leads a rebellion against a totalitarian regime." },
  { id: "plot-57", type: "plot", text: "trapped on Mt. Everest during a deadly storm." },
  { id: "plot-58", type: "plot", text: "will do anything for fame on a reality TV show." },
  { id: "plot-59", type: "plot", text: "discovers a hidden island full of mythical creatures." },
  { id: "plot-60", type: "plot", text: "tries to scam their way to fame in Hollywood." },
  { id: "plot-61", type: "plot", text: "hosts the worlds worst houseguest." },
  { id: "plot-62", type: "plot", text: "makes contact with dangerous aliens." },
  { id: "plot-63", type: "plot", text: "goes on a quest to slay a dragon." },
  { id: "plot-64", type: "plot", text: "hunts for elves in a mysterious forest." },
  { id: "plot-65", type: "plot", text: "goes on the run to escape deadly assassins." },
  { id: "plot-66", type: "plot", text: "searches for the cure of a deadly plague." },
  { id: "plot-67", type: "plot", text: "hunts and is hunted by a deadly serial killer." },
  { id: "plot-68", type: "plot", text: "is kidnapped by terrorists!" },
  { id: "plot-69", type: "plot", text: "is accidentally elected president of the United States." },
  { id: "plot-70", type: "plot", text: "treks across a dangerous desert to save their friends." },
  { id: "plot-71", type: "plot", text: "gets trapped in the body of a bear." },
  { id: "plot-72", type: "plot", text: "embarks on an epic journey to destroy an evil magical artifact." },
  { id: "plot-73", type: "plot", text: "only has one month to complete their bucket list." },
  { id: "plot-74", type: "plot", text: "competes against the rich kid team in a heartwarming underdog story." },
  { id: "plot-75", type: "plot", text: "fights to thwart an ancient and unstoppable evil." },
  { id: "plot-76", type: "plot", text: "outwits gangsters and cops in a series of death-defying car chases." },
  { id: "plot-77", type: "plot", text: "goes on a mad quest to kill the whale that ate their dog." },
  { id: "plot-78", type: "plot", text: "stranded on a lifeboat with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-79", type: "plot", text: "discovers a dangerous secret at a popular new theme park." },
  { id: "plot-80", type: "plot", text: "on a quest for a treasure that will save the kingdom." },
  { id: "plot-81", type: "plot", text: "must stop their evil twin from ruining their life!" },
  { id: "plot-82", type: "plot", text: "becomes a vigilante to rid their city of crime." },
  { id: "plot-83", type: "plot", text: "gets an exciting new job working for ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-84", type: "plot", text: "steals from the rich and gives to the poor and becomes a local legend." },
  { id: "plot-85", type: "plot", text: "attempts a desperate escape from Seaworld." },
  { id: "plot-86", type: "plot", text: "will do whatever it takes to become a world-famous chef." },
  { id: "plot-87", type: "plot", text: "fights in bloody gladiator death matches." },
  { id: "plot-88", type: "plot", text: "fights for the ultimate boxing title." },
  { id: "plot-89", type: "plot", text: "discovers the mythical city of El Dorado." },
  { id: "plot-90", type: "plot", text: "competes in a deadly underground martial arts tournament." },
  { id: "plot-91", type: "plot", text: "tries to steal the Declaration of Independence." },
  { id: "plot-92", type: "plot", text: "inherits an evil doll." },
  { id: "plot-93", type: "plot", text: "fights to stop an evil AI from destroying humanity." },
  { id: "plot-94", type: "plot", text: "faces a difficult choice between love and money." },
  { id: "plot-95", type: "plot", text: "receives an unexpected message from God." },
  { id: "plot-96", type: "plot", text: "leads the rescue mission for a missing child." },
  { id: "plot-97", type: "plot", text: "wins big at a casino and becomes the target of the mafia." },
  { id: "plot-98", type: "plot", text: "tries to capture a giant ape on a mysterious island." },
  { id: "plot-99", type: "plot", text: "fights a huge angry bear." },
  { id: "plot-100", type: "plot", text: "battles corruption in the greeting card industry." },
  { id: "plot-101", type: "plot", text: "on a deadly white-water rafting trip." },
  { id: "plot-102", type: "plot", text: "fights in a boxing match against their ultimate rival: ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-103", type: "plot", text: "building a rocketship to escape a dying planet." },
  { id: "plot-104", type: "plot", text: "accidentally joins a cult on their first day in college." },
  { id: "plot-105", type: "plot", text: "involved in a complicated love triangle." },
  { id: "plot-106", type: "plot", text: "leads a slave rebellion in ancient Rome." },
  { id: "plot-107", type: "plot", text: "fights against evil robots that look like people." },
  { id: "plot-108", type: "plot", text: "discovers the fountain of youth." },
  { id: "plot-109", type: "plot", text: "flees from a tribe of cannibals." },
  { id: "plot-110", type: "plot", text: "in a series of romantic misadventures." },
  { id: "plot-111", type: "plot", text: "falls madly in love with ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-112", type: "plot", text: "discovers a map leading to a legendary treasure hoard." },
  { id: "plot-113", type: "plot", text: "on a quest to discover Atlantis." },
  { id: "plot-114", type: "plot", text: "fights to save a rare and mysterious animal from poachers." },
  { id: "plot-115", type: "plot", text: "plots to escape a retirement home in Florida." },
  { id: "plot-116", type: "plot", text: "attempts to rescue hostages from a skyscraper." },
  { id: "plot-117", type: "plot", text: "tries to steal the worlds largest diamond." },
  { id: "plot-118", type: "plot", text: "fights to take down a dangerous cult." },
  { id: "plot-119", type: "plot", text: "struggles to bring their best friend back from the dead." },
  { id: "plot-120", type: "plot", text: "competes on a cooking game show to pay for their mom's medical bills." },
  { id: "plot-121", type: "plot", text: "matches wits against a wily leprechaun." },
  { id: "plot-122", type: "plot", text: "struggles to survive after a deadly shipwreck." },
  { id: "plot-123", type: "plot", text: "gets trapped overnight in a haunted asylum." },
  { id: "plot-124", type: "plot", text: "discovers a conspiracy of lizard people in the government." },
  { id: "plot-125", type: "plot", text: "has just two hours to find a huge amount of money for a dangerous mobster." },
  { id: "plot-126", type: "plot", text: "must protect their small village from a horde of bandits." },
  { id: "plot-127", type: "plot", text: "leads a ragtag crew of pirates against the British Navy." },
  { id: "plot-128", type: "plot", text: "is abducted by aliens!" },
  { id: "plot-129", type: "plot", text: "makes a selfish wish in a demonic wishing well." },
  { id: "plot-130", type: "plot", text: "haunted by the angry ghost of ____.", draws: [{ deck: "character", count: 1 }] },
  { id: "plot-131", type: "plot", text: "searches for peace in a dangerous radioactive wasteland." },
  { id: "plot-132", type: "plot", text: "is stranded on a desert island." },
  { id: "plot-133", type: "plot", text: "tries to save a family of Bigfoots from a deadly wildfire." },
  { id: "plot-134", type: "plot", text: "struggles to write the next great American novel." },
  { id: "plot-135", type: "plot", text: "fights to save their family from demonic possession." },
  { id: "plot-136", type: "plot", text: "will do whatever it takes to save the local library." },
  { id: "plot-137", type: "plot", text: "struggles to rebuild their community after a devastating hurricane." },
  { id: "plot-138", type: "plot", text: "accidentally becomes the Pope." },
  { id: "plot-139", type: "plot", text: "falls in love with a merperson." },
  { id: "plot-140", type: "plot", text: "tries to escape from the sinking city of Atlantis." },
  { id: "plot-141", type: "plot", text: "becomes worshipped as gods by a primitive culture." },
  { id: "plot-142", type: "plot", text: "battles an evil possessed book in a bookstore." },
  { id: "plot-143", type: "plot", text: "trapped in a dark version of our own reality." },
  { id: "plot-144", type: "plot", text: "goes for gold in Olympic figure skating." },
  { id: "plot-145", type: "plot", text: "must win enough money at the talent show to pay for their grandma's surgery." },
  { id: "plot-146", type: "plot", text: "searches for a stolen nuclear bomb." },
  { id: "plot-147", type: "plot", text: "goes on a dangerous ocean voyage." },
  { id: "plot-148", type: "plot", text: "tries to save their small beach town from a monstrous seal." },
  { id: "plot-149", type: "plot", text: "is held hostage at a karaoke bar run by monsters." },
  { id: "plot-150", type: "plot", text: "discovers the secret world of modern wizards." },
  { id: "plot-151", type: "plot", text: "fights a supernatural killer clown." },
  { id: "plot-152", type: "plot", text: "goes on a quest for the Holy Grail." },
  { id: "plot-153", type: "plot", text: "goes back in time to kill Hitler." },
  { id: "plot-154", type: "plot", text: "protecting the world's last unicorn from an evil cosmetics company." },
  { id: "plot-155", type: "plot", text: "flees from natural disaster in a near-future apocalypse." },
  { id: "plot-156", type: "plot", text: "learns that they are heir to the throne of an ancient kingdom." },
  { id: "plot-157", type: "plot", text: "discovering the true origins of Santa Claus." },
  { id: "plot-158", type: "plot", text: "steals a magical treasure from a dangerous witch." },
  { id: "plot-159", type: "plot", text: "navigates the secret world of modern vampires." },
  { id: "plot-160", type: "plot", text: "Choose the plot of your favourite video game. Your movie is an adaptation of that plot.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-161", type: "plot", text: "Choose a plot previously pitched by another player. Your movie is a broadway adaptation of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-162", type: "plot", text: "Choose a plot previously pitched by another player. Your movie is a hilarious spoof of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-163", type: "plot", text: "Choose the plot to your favourite movie. Your movie is a gritty reboot of that idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-164", type: "plot", text: "Choose the plot to your favourite book. Your movie is an adaptation of that book.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-165", type: "plot", text: "Choose a plot previously pitched. Your movie is a gritty reboot of their idea.", header: "FRANCHISE PITCH:", isFranchise: true },
  { id: "plot-166", type: "plot", text: "Choose the plot of your favourite movie. This is another sequel to that movie.", header: "FRANCHISE PITCH:", isFranchise: true },
];

const CHARACTER_CARDS: Card[] = [
  { id: "char-1", type: "character", header: "EXT. DREARY ORPHANAGE", text: "A sad, sad orphan looking for a new family" },
  { id: "char-2", type: "character", header: "EXT. OUT BY THE WELL", text: "A dog just trying to rescue his boy" },
  { id: "char-3", type: "character", header: "INT. COMMAND CENTER", text: "A heroic young naval officer" },
  { id: "char-4", type: "character", header: "EXT. JUNKYARD", text: "A dog who never had a home" },
  { id: "char-5", type: "character", header: "INT. TOP-SECRET FACILITY", text: "The world's first sentient A.I." },
  { id: "char-6", type: "character", header: "EXT. CITY ROOFTOPS", text: "An untrained vigilante" },
  { id: "char-7", type: "character", header: "INT. YMCA", text: "A senior citizen swim team" },
  { id: "char-8", type: "character", header: "EXT. FRUIT MARKET", text: "A pineapple with a heart of gold" },
  { id: "char-9", type: "character", header: "INT. BUSY RESTAURANT", text: "A clumsy but loveable waitress" },
  { id: "char-10", type: "character", header: "INT. GROCERY STORE", text: "An authoritarian grocery store manager" },
  { id: "char-11", type: "character", header: "EXT. RUN-DOWN HOUSE", text: "A witch living on the edge of town" },
  { id: "char-12", type: "character", header: "INT. JEFF'S BASEMENT", text: "A pair of stoners that just ran out of weed" },
  { id: "char-13", type: "character", header: "EXT. THE SIDE OF THE ROAD", text: "A dysfunctional family on a road trip" },
  { id: "char-14", type: "character", header: "INT. KARAOKE BAR", text: "A country singer determined to make it big in Nashville" },
  { id: "char-15", type: "character", header: "INT. HIGH-SECURITY LAB", text: "A group of scientists on the brink of resurrecting dinosaurs" },
  { id: "char-16", type: "character", header: "INT. OIL FIELDS", text: "A corrupt oil baron that will do anything for profit" },
  { id: "char-17", type: "character", header: "INT. CITY LIBRARY", text: "A bookish librarian that just wants to be left alone" },
  { id: "char-18", type: "character", header: "EXT. PARISIAN STREET", text: "A mime with magical powers" },
  { id: "char-19", type: "character", header: "EXT. DAYCARE CENTER", text: "An overworked single parent" },
  { id: "char-20", type: "character", header: "INT. CELEBRITY MANSION", text: "The producer of a trashy reality show" },
  { id: "char-21", type: "character", header: "INT. ARCADE", text: "A videogame character comes to life" },
  { id: "char-22", type: "character", header: "INT. POLICE STATION", text: "An innocent person framed for murder" },
  { id: "char-23", type: "character", header: "EXT. TRANSYLVANIAN CASTLE", text: "An ancient and powerful vampire" },
  { id: "char-24", type: "character", header: "INT. KITCHEN", text: "A small mouse with a big heart" },
  { id: "char-25", type: "character", header: "EXT. CELEBRITY MANSION", text: "An A-list Hollywood star on the edge of bankruptcy" },
  { id: "char-26", type: "character", header: "INT. BAND CLASS", text: "The world's hottest oboe player" },
  { id: "char-27", type: "character", header: "EXT. MYSTERIOUS FOREST", text: "A friendly dragon living in the forest" },
  { id: "char-28", type: "character", header: "INT. WIZARD'S STUDY", text: "An old wizard in need of an apprentice" },
  { id: "char-29", type: "character", header: "EXT. THE JUNGLE", text: "A feral child raised by apes" },
  { id: "char-30", type: "character", header: "INT. HOSPITAL", text: "A surgeon with a fake medical degree" },
  { id: "char-31", type: "character", header: "EXT. THE OPEN OCEAN", text: "The passengers of an ill-fated luxury cruise" },
  { id: "char-32", type: "character", header: "INT. MANSION", text: "The leader of a powerful mob family" },
  { id: "char-33", type: "character", header: "INT. DIVE BAR", text: "An amateur metal band struggling to find a gig" },
  { id: "char-34", type: "character", header: "INT. ARCADE", text: "A charismatic slacker just out for a good time" },
  { id: "char-35", type: "character", header: "EXT. FOOTBALL FIELD", text: "A huge jock that just wants to be a ballerina" },
  { id: "char-36", type: "character", header: "INT. THE BRIDGE", text: "The roguish captain of an interstellar starship" },
  { id: "char-37", type: "character", header: "EXT. THE GRAND CANYON", text: "A daredevil with a deathwish" },
  { id: "char-38", type: "character", header: "INT. HAUNTED HOUSE", text: "A woman that can speak to ghosts" },
  { id: "char-39", type: "character", header: "INT. THE WHITE HOUSE", text: "The U.S. President" },
  { id: "char-40", type: "character", header: "INT. ANIMAL SHELTER", text: "The world's most adorable kitten" },
  { id: "char-41", type: "character", header: "EXT. ANCIENT RUINS", text: "A professor turned adventurer" },
  { id: "char-42", type: "character", header: "EXT. THE EDGE OF TOWN", text: "An old widow that everyone thinks is a witch" },
  { id: "char-43", type: "character", header: "INT. AREA 51", text: "A secret government agency protecting the world from aliens" },
  { id: "char-44", type: "character", header: "EXT. OLD WESTERN SALOON", text: "A cowboy left for dead and out for revenge" },
  { id: "char-45", type: "character", header: "EXT. BEHIND ENEMY LINES", text: "A group of soldiers on a suicide mission" },
  { id: "char-46", type: "character", header: "INT. GOVERNOR'S MANSION", text: "A magical nanny for a wealthy family" },
  { id: "char-47", type: "character", header: "EXT. FEUDAL JAPAN", text: "A young ninja on a quest to avenge their family" },
  { id: "char-48", type: "character", header: "EXT. THE OPEN ROAD", text: "A mysterious drifter from their past" },
  { id: "char-49", type: "character", header: "INT. DENNY'S", text: "A misunderstood old man" },
  { id: "char-50", type: "character", header: "INT. WALMART", text: "A has-been professional wrestler" },
  { id: "char-51", type: "character", header: "EXT. DEEP IN THE WOODS", text: "Two kids lost in the woods" },
  { id: "char-52", type: "character", header: "EXT. MYSTERIOUS ISLAND", text: "A crew of pirates on the hunt for treasure" },
  { id: "char-53", type: "character", header: "EXT. FIELDS OF BATTLE", text: "A noble barbarian from a distant land" },
  { id: "char-54", type: "character", header: "INT. HIP VAMPIRE CLUB", text: "An overweight vampire that just wants to fit in" },
  { id: "char-55", type: "character", header: "EXT. BAMBOO FOREST", text: "A young samurai on a quest to prove themselves" },
  { id: "char-56", type: "character", header: "INT. THE OPERATING ROOM", text: "An ensemble cast of sexy young E.R. doctors" },
  { id: "char-57", type: "character", header: "EXT. THE ENCHANTED FOREST", text: "Three little homeless pigs" },
  { id: "char-58", type: "character", header: "INT. THE EMBASSY", text: "A secret agent whose cover has just been blown" },
  { id: "char-59", type: "character", header: "INT. HEADMASTER'S STUDY", text: "The headmaster of a strict boarding school" },
  { id: "char-60", type: "character", header: "EXT. WORKING CLASS TOWN", text: "A grizzled veteran returning home" },
  { id: "char-61", type: "character", header: "INT. INTERNET CAFE", text: "The best hacker in the world" },
  { id: "char-62", type: "character", header: "EXT. THE COLISEUM", text: "A disgraced Roman general" },
  { id: "char-63", type: "character", header: "INT. MT. OLYMPUS", text: "Zeus, king of the gods" },
  { id: "char-64", type: "character", header: "INT. DINGY APARTMENT", text: "A desperate con artist struggling to feed their family" },
  { id: "char-65", type: "character", header: "EXT. THE OUTBACK", text: "A crocodile hunter who knows nothing about the big city" },
  { id: "char-66", type: "character", header: "EXT. MARTIAN DESERT", text: "The first human colonists on Mars" },
  { id: "char-67", type: "character", header: "EXT. DARK ALLEY", text: "A young superhero just discovering their powers" },
  { id: "char-68", type: "character", header: "EXT. CAMELOT", text: "The Knights of the Round Table" },
  { id: "char-69", type: "character", header: "INT. PRISTINE LAWN", text: "A grumpy old man that just wants his privacy" },
  { id: "char-70", type: "character", header: "EXT. GRUNGY STREET", text: "A professional hitman on their last job" },
  { id: "char-71", type: "character", header: "INT. CHILDREN'S HOSPITAL", text: "A friendly clown on a mission to make people happy" },
  { id: "char-72", type: "character", header: "INT. CONVENT", text: "A nun with a scandalous secret" },
  { id: "char-73", type: "character", header: "INT. CASTLE TOWER", text: "A princess determined to rescue herself" },
  { id: "char-74", type: "character", header: "EXT. DENNY'S PARKING LOT", text: "A group of friends on their last night before they all leave for college" },
  { id: "char-75", type: "character", header: "EXT. THE MAYOR'S OFFICE", text: "A ruthless politician hungry for power" },
  { id: "char-76", type: "character", header: "INT. LOFT APARTMENT", text: "A young artist struggling to pay rent" },
  { id: "char-77", type: "character", header: "EXT. SOCCER FIELD", text: "A soccer mom that is determined to help her kids win the big game" },
  { id: "char-78", type: "character", header: "INT. CHILD'S BEDROOM", text: "A childhood toy come to life" },
  { id: "char-79", type: "character", header: "INT. CHURCH BASEMENT", text: "A hip rapping youth pastor" },
  { id: "char-80", type: "character", header: "EXT. TUNDRA", text: "A tribe of cavemen hunting for food" },
  { id: "char-81", type: "character", header: "INT. FRAT HOUSE", text: "A fraternity on the verge of suspension" },
  { id: "char-82", type: "character", header: "INT. ART GALLERY", text: "A suave art thief" },
  { id: "char-83", type: "character", header: "EXT. STORMY SEA", text: "A grizzled sea captain" },
  { id: "char-84", type: "character", header: "INT. DOJO", text: "A martial arts master with a troubled past" },
  { id: "char-85", type: "character", header: "INT. TIDY APARTMENT", text: "A blind woman living by herself" },
  { id: "char-86", type: "character", header: "EXT. NEW YORK CITY", text: "Crime-fighting robots" },
  { id: "char-87", type: "character", header: "INT. INDUSTRIAL SITE", text: "Two secret agents deep undercover" },
  { id: "char-88", type: "character", header: "EXT. HIGH SCHOOL GYM", text: "A group of teens charged with protecting the world" },
  { id: "char-89", type: "character", header: "INT. COUNTRY CLERK'S OFFICE", text: "A journalist on the trail of a huge story" },
  { id: "char-90", type: "character", header: "INT. DIRTY APARTMENT", text: "A divorced dad trying to reconnect with his kids" },
  { id: "char-91", type: "character", header: "INT. SUBURBAN HOME", text: "A married couple going through a nasty divorce" },
  { id: "char-92", type: "character", header: "EXT. CONSTRUCTION SITE", text: "Friendly woodland creatures forced to flee their home because of pollution" },
  { id: "char-93", type: "character", header: "INT. THE GLOBE THEATRE", text: "Hot young William Shakespeare" },
  { id: "char-94", type: "character", header: "EXT. CENTRAL PARK", text: "A friendly talking dinosaur" },
  { id: "char-95", type: "character", header: "INT. AT THE CLUB", text: "A lifelong bachelor" },
  { id: "char-96", type: "character", header: "INT. CLONING LAB", text: "(Pick a historical figure)" },
  { id: "char-97", type: "character", header: "INT. CHILDREN'S THEATRE", text: "The world's greatest puppeteer" },
  { id: "char-98", type: "character", header: "INT. MANHATTAN OFFICE", text: "A sports writer looking for love" },
  { id: "char-99", type: "character", header: "EXT. ABANDONED HOUSE", text: "Confused ghosts that don't know they're dead" },
  { id: "char-100", type: "character", header: "EXT. DOWN THE STREET", text: "A group of kids solving a mystery at summer camp" },
  { id: "char-101", type: "character", header: "INT. RESEARCH FACILITY", text: "A troubled kid with supernatural powers" },
  { id: "char-102", type: "character", header: "INT. REBEL SPACESHIP", text: "A ragtag group of rebels" },
  { id: "char-103", type: "character", header: "EXT. FARM", text: "A little girl and her dog" },
  { id: "char-104", type: "character", header: "EXT. BOSTON WHARF", text: "A young gangster that will do anything to get to the top" },
  { id: "char-105", type: "character", header: "INT. MYSTERIOUS CAVE", text: "A genie trapped in a magic lamp" },
  { id: "char-106", type: "character", header: "INT. RURAL CHURCH", text: "A beguiling cult leader" },
  { id: "char-107", type: "character", header: "INT. SUSHI RESTAURANT", text: "A young couple on the verge of breaking up" },
  { id: "char-108", type: "character", header: "EXT. FOOTBALL FIELD", text: "A controversial small town football coach" },
  { id: "char-109", type: "character", header: "INT. UNDERSEA LABORATORY", text: "A shark with a human brain" },
  { id: "char-110", type: "character", header: "EXT. TROOP 514 TURF", text: "A gang of ruthless girl scouts" },
  { id: "char-111", type: "character", header: "EXT. DREARY GRAVEYARD", text: "A lonely gravedigger" },
  { id: "char-112", type: "character", header: "INT. AUDITION ROOM", text: "A plucky down-on-her-luck actress" },
  { id: "char-113", type: "character", header: "EXT. LOS ANGELES", text: "(Pick an actor/actress) Playing themselves" },
  { id: "char-114", type: "character", header: "INT. POLICE STATION", text: "A cop that plays it by the book" },
  { id: "char-115", type: "character", header: "INT. THE PRINCIPAL'S OFFICE", text: "A child genius with no social skills" },
  { id: "char-116", type: "character", header: "EXT. AT THE CLUB", text: "A fiery young rapper on their way to fame" },
  { id: "char-117", type: "character", header: "EXT. THE GARDEN", text: "An aging butler reminiscing about their glory days" },
  { id: "char-118", type: "character", header: "EXT. MEDIEVAL CASTLE", text: "A knight sworn to protect their kingdom" },
  { id: "char-119", type: "character", header: "INT. HUMAN HOME", text: "A bear disguised as a person" },
  { id: "char-120", type: "character", header: "INT. DINGY OFFICE", text: "A private detective following a dangerous trail of clues" },
  { id: "char-121", type: "character", header: "INT. AUTO-SHOP", text: "A down-on-their-luck auto mechanic" },
  { id: "char-122", type: "character", header: "EXT. STONE BRIDGE", text: "A misunderstood troll living under a bridge" },
  { id: "char-123", type: "character", header: "INT. BARRACKS", text: "A group of kids at boot camp" },
  { id: "char-124", type: "character", header: "INT. CONFESSIONAL BOOTH", text: "A priest suffering a crisis of faith" },
  { id: "char-125", type: "character", header: "INT. LIBRARY", text: "A fed up high school librarian with nothing to lose" },
  { id: "char-126", type: "character", header: "INT. VW BUS", text: "An aging hippie that longs for the good ole days" },
  { id: "char-127", type: "character", header: "INT. SWISS BANK", text: "A deadly assassin suffering from amnesia" },
  { id: "char-128", type: "character", header: "EXT. IDYLLIC VILLAGE", text: "A fellowship of unlikely heroes" },
  { id: "char-129", type: "character", header: "INT. GAMBLING HALL", text: "Two scoundrels out to make a fortune" },
  { id: "char-130", type: "character", header: "INT. BEAUTY PAGEANT", text: "A child beauty pageant queen" },
  { id: "char-131", type: "character", header: "INT. MODERN ART MUSEUM", text: "A snobby art critic" },
  { id: "char-132", type: "character", header: "EXT. RECESS", text: "The world's meanest ten-year-old bully" },
  { id: "char-133", type: "character", header: "INT. AIRPORT SECURITY", text: "A TSA agent fighting for justice" },
  { id: "char-134", type: "character", header: "EXT. THE WOODS", text: "A bunch of kids looking for adventure during summer vacation" },
  { id: "char-135", type: "character", header: "INT. BACKSTAGE", text: "An ambitious young pop-star" },
  { id: "char-136", type: "character", header: "INT. 1-BEDROOM APARTMENT", text: "A cat that will do anything to get fed" },
  { id: "char-137", type: "character", header: "EXT. MYSTERIOUS CASTLE", text: "A mad scientist conducting a world-changing experiment" },
  { id: "char-138", type: "character", header: "INT. ENCHANTED CASTLE", text: "A prince transformed into a monster" },
  { id: "char-139", type: "character", header: "INT. LIBERTY HALL", text: "The Founding Fathers" },
  { id: "char-140", type: "character", header: "INT. ASTRONOMY LAB", text: "An astronomer that thinks they've made contact with aliens" },
  { id: "char-141", type: "character", header: "INT. DINING HALL", text: "A lonely child at a boarding school" },
  { id: "char-142", type: "character", header: "EXT. TINY FISHING BOAT", text: "An old fisherman alone at sea" },
  { id: "char-143", type: "character", header: "INT. WASHINGTON D.C.", text: "A young politician with dreams of saving the world" },
  { id: "char-144", type: "character", header: "INT. CHILD'S BEDROOM", text: "A kid with a creepy imaginary friend" },
  { id: "char-145", type: "character", header: "INT. COFFEE SHOP", text: "A caveman recently brought back to life" },
  { id: "char-146", type: "character", header: "INT. NURSERY", text: "A wise-cracking baby" },
  { id: "char-147", type: "character", header: "EXT. MEXICAN RESORT TOWN", text: "A group of girls out for the BEST SPRING BREAK EVER" },
  { id: "char-148", type: "character", header: "EXT. WINDSWEPT PRAIRIE", text: "A stoic family of pioneers" },
  { id: "char-149", type: "character", header: "EXT. BBQ SHED", text: "A family of cannibal hillbillies" },
  { id: "char-150", type: "character", header: "EXT. HOLLYWOOD PARTY", text: "An ensemble cast of celebrities playing themselves" },
  { id: "char-151", type: "character", header: "INT. ICE SKATING RINK", text: "A competitive figure skater training to win the Grand Prix" },
  { id: "char-152", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie stars a younger version of that character.", isFranchise: true },
  { id: "char-153", type: "character", header: "FRANCHISE PITCH:", text: "Choose a mentor character from another player's previously pitched movie. Your movie is an origin story for that character.", isFranchise: true },
  { id: "char-154", type: "character", header: "FRANCHISE PITCH:", text: "Choose a love interest from another player's previously pitched movie.", isFranchise: true },
  { id: "char-155", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie is an off-brand knock off of their character.", isFranchise: true },
  { id: "char-156", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie features them as a grizzled veteran.", isFranchise: true },
  { id: "char-157", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie is about that character's children.", isFranchise: true },
  { id: "char-158", type: "character", header: "FRANCHISE PITCH:", text: "Choose a minor character from another player's previously pitched movie.", isFranchise: true },
  { id: "char-159", type: "character", header: "FRANCHISE PITCH:", text: "Choose a villain from another player's previously pitched movie.", isFranchise: true },
  { id: "char-160", type: "character", header: "FRANCHISE PITCH:", text: "Choose the hero of another player's previously pitched movie.", isFranchise: true },
  { id: "char-161", type: "character", header: "FRANCHISE PITCH:", text: "Choose a character from another player's previously pitched movie. Your movie is the third movie in that trilogy.", isFranchise: true },
];

const NOTE_CARDS: Card[] = [
  { id: "note-1", type: "note", text: "Add a musical number" },
  { id: "note-2", type: "note", text: "The lead actor must cry for real" },
  { id: "note-3", type: "note", text: "Include a 5-minute car chase" },
  { id: "note-4", type: "note", text: "The villain must be the hero's own reflection" },
  { id: "note-5", type: "note", text: "Everyone in the movie must speak in rhyme" },
  { id: "note-6", type: "note", text: "Add a flashback to a flashback" },
  { id: "note-7", type: "note", text: "The movie must end on a cliffhanger" },
  { id: "note-8", type: "note", text: "Add a CGI talking animal sidekick" },
  { id: "note-9", type: "note", text: "The soundtrack must be entirely kazoos" },
  { id: "note-10", type: "note", text: "Halfway through, the movie must switch genres" },
];

export function getSeedCards(): { plot: Card[]; character: Card[]; note: Card[] } {
  return { plot: PLOT_CARDS, character: CHARACTER_CARDS, note: NOTE_CARDS };
}